### ISSUE TITLE
Separate TSV files for heating/cooling type and efficiency

### ISSUE THREAD

**Issue by ejhw** [NREL/resstock#100]
It would be helpful for Radiant Labs if we had separate TSV files for heating/cooling type and efficiency. This would allow them to use the heating/cooling system type data from assessors' databases, whereas they cannot currently because they don't know the efficiency.

We've actually done something similar for cooling type for mapping to AHS data: https://github.com/NREL/OpenStudio-BuildStock/blob/master/project_resstock_national/housing_characteristics/HVAC%20System%20Cooling%20Type.tsv However, we would want to flip the hierarchy so that it goes cooling type --> cooling efficiency.

@shorowit Any reason you think this wouldn't be a good idea?

**Comment by ejhw** [comment]
After discussing, we may do this in the future, but @shorowit had another, easier, idea for Radiant Labs to try.

**Comment by shorowit** [comment]
There are now separate TSVs for type vs efficiency: https://github.com/NREL/resstock/tree/develop/project_national/housing_characteristics
