### ISSUE TITLE
Make `NumApplyUpgradeOptions` dynamic

### ISSUE THREAD

**Issue by lixiliu** [NREL/resstock#1005]
## Description

`NumApplyUpgradeOptions` is a constant parameter default to 25. It would be great to make the parameter dynamically determined based on actual upgrades in a yaml file, especially as upgrade runs are getting more complicated to specify (requiring many options) and more numerous generally and we don't always remember to modify this parameter for large upgrade runs, especially when it's buried deep inside the measure too.

https://github.com/NREL/resstock/blob/81734120c11055d495223f7fc2e83c4b089f99da/measures/ApplyUpgrade/resources/constants.rb#L3-L5

## Progress

- [ ] Validation check in bsb: https://github.com/NREL/buildstockbatch/pull/330
- [ ] Dynamically update [measure.xml](https://github.com/NREL/resstock/blob/develop/measures/ApplyUpgrade/measure.xml)

**Comment by afontani** [comment]
@nmerket : Thoughts?

**Comment by nmerket** [comment]
I think it's a good idea, but my understanding was that we needed to have that constant because the [measure.xml](https://github.com/NREL/resstock/blob/develop/measures/ApplyUpgrade/measure.xml) needs to be updated as well and there's not a way to make that automatic. Maybe @joseph-robertson remembers...

**Comment by joseph-robertson** [comment]
Yes @nmerket that is correct. You can see in the linked measure.xml that arguments go up to `option_25_xxx`. Perhaps we could update measure.xml files on the fly or something...

**Comment by nmerket** [comment]
How does that measure.xml get updated these days? In the olden days of PAT, we would just open the in the OpenStudio GUI application. Is there a command on the CLI that updates measures now?

**Comment by joseph-robertson** [comment]
By running `openstudio tasks.rb update_measures`. See [here](https://github.com/NREL/resstock/blob/develop/tasks.rb#L47).

**Comment by shorowit** [comment]
If you just want to update the single measure's xml: `openstudio measure -u measures/ApplyUpgrade`

**Comment by nmerket** [comment]
Rather than trying to edit files that are committed in the repository at runtime we should take the approach in https://github.com/NREL/buildstockbatch/issues/329 and make a validator on buildstockbatch that give a helpful error message about how to update the measure.

**Comment by ekpresent** [comment]
I think even just something that would catch the issue before running would be a big improvement over the status quo. "Upgrade x has y options, and you are currently configured for z max. See documentation for how to change this." or some more succinct version. I'd rather have that ( https://github.com/NREL/buildstockbatch/issues/329) sooner than this (https://github.com/NREL/resstock/issues/1005) a few months later.

**Comment by joseph-robertson** [comment]
@nmerket @ekpresent So implement https://github.com/NREL/buildstockbatch/issues/329 now and leave _this_ issue for possible implementation later?

**Comment by nmerket** [comment]
I think so. I have a PR open for this that I need to polish up https://github.com/NREL/buildstockbatch/pull/330, but I think we're just about there.

**Comment by afontani** [comment]
To close let's just add documentation around how to do this on HPC (Eagle). @nmerket to improve Wiki (https://github.com/NREL/buildstockbatch/wiki/Adding-Options-to-the-ApplyUpgrade-measure)

**Comment by nmerket** [comment]
I added some instructions to the wiki about how to run the upgrade measure command on Eagle via Singularity.
