### ISSUE TITLE
rogue `FIXME`s  in 'Water Heater Efficiency' options?

### ISSUE THREAD

**Issue by spolloni** [NREL/resstock#1010]
https://github.com/NREL/resstock/blob/ee49ad68b9bd87fae5045218b3ea0f0d6f7daada/project_testing/housing_characteristics/Solar%20Hot%20Water.tsv#L9

this seems to have propagated into the metadata files of the [End Use Savings Shapes](https://resstock.nrel.gov/datasets)

**Comment by joseph-robertson** [comment]
The "FIXME" string is intentionally inserted into the "Oil Indirect" Water Heater Efficiency option. It is used to denote that we currently model a "storage water heater" instead of a "space-heating boiler with storage tank" (i.e., combi boiler/tank system).

**Comment by rajeee** [comment]
Related to: https://github.com/NREL/resstock-estimation/issues/61
