### ISSUE TITLE
How many decimal places for timeseries output?

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/resstock#1016]
Currently, it defaults to 3 places. Should it be higher? Should users be able to control this number?

See https://github.com/NREL/OpenStudio-HPXML/pull/1260.

**Comment by rajeee** [comment]
I recommend 5.
https://github.com/NREL/OpenStudio-HPXML/pull/1260#issuecomment-1371543868

**Comment by joseph-robertson** [comment]
@nmerket Based on @rajeee's recommendation here, I wonder if we should add `'timeseries_num_decimal_places': 5` into the wfg (and thus break backward compatibility) in https://github.com/NREL/buildstockbatch/pull/337?

**Comment by joseph-robertson** [comment]
Ah right, we did talk about that. Do we have a precedent (example) for doing that? Perhaps by looking at the measure.xml?

**Comment by nmerket** [comment]
I don't know if we have a good example of that. I know there's some reading the measure.xml in some of the validators, but that would be a good approach.

Ultimately we should switch to msgpack by default in resstock. Those numbers are being rounded there, so [that will need to be addressed first](https://github.com/NREL/OpenStudio-HPXML/issues/1262).

**Comment by rajeee** [comment]
Decided to keep 3 digits.
