### ISSUE TITLE
Data viewer downloads of 2012 AMY data have 2016 timestamps

### ISSUE THREAD

**Issue by mcpigman** [NREL/resstock#1018]
The timeseries files for the 2012 AMY data downloaded from the data viewer have timestamps in 2016. (The aggregate files from the data lake are 2012 as expected.)

**Comment by ekpresent** [comment]
I vote @nmerket

**Comment by nmerket** [comment]
Fixed in https://github.com/NREL/SightGlass/pull/284. Need to merge and deploy that.

**Comment by nmerket** [comment]
Deployed the fixed version to the website.
