### ISSUE TITLE
Add diversity in spot ventilation and vacations

### ISSUE THREAD

**Issue by ejhw** [NREL/resstock#102]
#### Approach: 
- TSV to specify daily time of spot vent? Probability based on occupant schedule?
## Vacations
- TSV for 365 day shifts (all equal probability)

cc @shorowit @jmaguire1 

- [x] Spot vent
- [ ] Vacations

**Comment by joseph-robertson** [comment]
I think Jeff already made the 365 day shifts one: https://github.com/NREL/OpenStudio-BuildStock/blob/master/project_resstock_national/housing_characteristics/Days%20Shifted.tsv.

**Comment by ejhw** [comment]
Cool, we can use that for both DHW draws and vacations.

**Comment by ejhw** [comment]
@jmaguire1 Would you be able to work on applying your DaysShifted.tsv to vacations?

**Comment by jmaguire1** [comment]
Yeah I should have time but we should talk about what exactly you're looking to do before I get started.

**Comment by afontani** [comment]
Closing this with the mention of modeling vacations. https://github.com/NREL/resstock/issues/998

**Comment by shorowit** [comment]
I don't see a Days Shifted.tsv in the develop branch of resstock, so this may not currently be implemented.
