### ISSUE TITLE
Update to 2022 Cambium release

### ISSUE THREAD

**Issue by mdahlhausen** [NREL/resstock#1033]
Resstock and Comstock are using 2021 Cambium data.
https://github.com/NREL/resstock/tree/develop/resources/data/cambium

Cambium 2022 data is out.  This issue is to update to the 2022 data.

**Comment by joseph-robertson** [comment]
Do we want to add the 2022 data (and retain 2021), or replace 2021 with 2022?

**Comment by mdahlhausen** [comment]
@joseph-robertson I think replacing is fine.  Also it'd be nice to use month-hour values instead of 8760 values.

**Comment by joseph-robertson** [comment]
For month-hour support, I think you'd need to submit a feature request on https://github.com/NREL/OpenStudio-HPXML.

**Comment by mdahlhausen** [comment]
Nevermind; I was reading some of the data wrong.  The _15 and _30 data is month-hour in 8760 format, and that format is fine.  I was looking at the _1 directories which appear to use 8760 hourly data.

**Comment by shorowit** [comment]
> For month-hour support, I think you'd need to submit a feature request on https://github.com/NREL/OpenStudio-HPXML.

You can provide month-hour values in 8760 format. (That's what we do for ERI calculations.)
