### ISSUE TITLE
Pool and Hot Tub schedules are NOT nullified for vacant units

### ISSUE THREAD

**Issue by lixiliu** [NREL/resstock#1047]
These are a few buildings from EUSS 1.0 AMY2018 run:
<img width="773" alt="Screen Shot 2023-03-08 at 7 12 47 PM" src="https://user-images.githubusercontent.com/36629962/223897976-b9863257-ec73-4748-bfa2-2817e663a42c.png">

I check their run/schedules.csv, the following columns are not nullified for vacant units:
- pool_pump
- pool_heater
- hot_tub_pump
- hot_tub_heater

**Why is that?**
[schedules_bldg_360746_vacant_pool.csv](https://github.com/NREL/resstock/files/10927018/schedules_bldg_360746_vacant_pool.csv)
[schedules_bldg_513245_occupied_pool.csv](https://github.com/NREL/resstock/files/10927021/schedules_bldg_513245_occupied_pool.csv)

**Comment by joseph-robertson** [comment]
This is intentional. The idea is that these schedules, along with refrigerator/freezer schedules, are not affected by vacancy. See https://github.com/NREL/OpenStudio-HPXML/blob/master/HPXMLtoOpenStudio/resources/schedules.rb#L1588-L1608.

**Comment by shorowit** [comment]
Looks like it was decided here: https://github.com/NREL/resstock/issues/562#issuecomment-806262789

**Comment by lixiliu** [comment]
Thanks good to know! Looks like the rationale is that these schedules aren't occupant-driven and are not easily modified by occupants when they vacay.

Good to close issue.

**Comment by shorowit** [comment]
Also note that there will be a [simple CSV file](https://github.com/NREL/OpenStudio-HPXML/blob/e7d9e764a15dde2f29b4b191ba3da8d07eee178c/HPXMLtoOpenStudio/resources/data/schedules_affected.csv) where you can turn end uses on or off in terms of how they behave during vacancies and power outages. This will be available in the near future when https://github.com/NREL/OpenStudio-HPXML/pull/1266 is merged and brought into ResStock.
