### ISSUE TITLE
Cambium start year harmonization

### ISSUE THREAD

**Issue by ekpresent** [NREL/resstock#1063]
Can we add the 2025 Start numbers we used for EUSS Residential Round 1 to the /develop branch (Cambium 2021) and also add 2025 Start numbers from Cambium 2022? Any analysis that wants to use the same numbers as EUSS Residential Round 1 will want the former, and I don't think we should be using historical start years in general. 

https://github.com/NREL/resstock/tree/run/euss/resources/data/cambium

**Comment by afontani** [comment]
From @joseph-robertson: Also consider using the Cambium API.

**Comment by afontani** [comment]
Retaining previous Cambium data in this related PR #1038.

**Comment by joseph-robertson** [comment]
We decided that adding 2025 start numbers from Cambium 2022 obviates the need for 2025 start numbers from Cambium 2021. Therefore, https://github.com/NREL/resstock/pull/1038 closes this issue.
