### ISSUE TITLE
Not all options in options_lookup.tsv are supported in projects_national lookups

### ISSUE THREAD

**Issue by jason-curtis** [NREL/resstock#1082]
I'm seeing a difference between the options in `options_lookup.tsv` and the dependency values in `projects_national/housing_characteristics/*.tsv`

## Expected:

* if I choose a combination of options from `options_lookup.tsv`, I can use the stats tables in projects_national to inform my choices of other options.
* Specfically, if I choose `Geometry Foundation Type = Conditioned Crawlspace` from [here](https://github.com/NREL/resstock/blob/develop/resources/options_lookup.tsv#L134), I expect to be able to use that option to inform choices of ducts in [Ducts.tsv](https://github.com/NREL/resstock/blob/develop/project_national/housing_characteristics/Ducts.tsv).

## Actual behavior:

`Conditioned Crawlspace` does not appear in `Ducts.tsv` so I can't do that. Only the other choices for `Geometry Foundation Type` appear to be supported in the probability tables.

## Question

Is this intended? I may have misunderstood the purpose of options_lookup.tsv but I expected them all to be supported. I'm not sure if `Geometry Foundation Type = Conditioned Crawlspace` is the only option like this.

cc @jmarrec

**Comment by joseph-robertson** [comment]
The `options_lookup.tsv` is just a map from options to sets of measure argument values. A project is not required to sample all of them. Think of it as the "superset" of all options. Meaning, they are allowed to exist in `options_lookup.tsv` even if `project_national` doesn't sample them. The `project_testing` project, on the other hand, is meant to "test" all options found in the lookup.

It's also possible that options from the lookup are intended to be "upgrade" options - you wouldn't find them in any housing characteristics TSV files (i.e., baseline), but they could be used to define upgrade scenarios in project yml files.

**Comment by jason-curtis** [comment]
Got it, thank you for the clarification!
