### ISSUE TITLE
Expose CompressorType variable for heat pumps

### ISSUE THREAD

**Issue by ekpresent** [NREL/resstock#1084]
The LARGEEE run wants to use ASHP speeds other than the ones that are currently assigned based on SEER in ResStock. Therefore we need the CompressorType variable exposed.

**Comment by joseph-robertson** [comment]
@ekpresent See https://openstudio-hpxml.readthedocs.io/en/latest/workflow_inputs.html#air-to-air-heat-pump for current capabilities/limitations here. While `heat_pump_cooling_compressor_type` is an argument we _could_ assign using the lookup, both `heat_pump_heating_efficiency` (e.g., HSPF) and `heat_pump_cooling_efficiency` (e.g., SEER) are still required.

Here is the map for defaulting compressor type based on SEER:
```
if seer <= 15
  return HPXML::HVACCompressorTypeSingleStage
elsif seer <= 21
  return HPXML::HVACCompressorTypeTwoStage
elsif seer > 21
  return HPXML::HVACCompressorTypeVariableSpeed
end
```

**Comment by ekpresent** [comment]
@joseph-robertson  the heat pumps specced for inclusion in the run include a SEER1 16 single stage and a SEER1 20 variable speed (per the advice of Jon and others), which is why we want the variable exposed. Jeff actually was able to point us to those lines in HVAC.rb that would mean both the SEER1 16 and the SEER1 20 would be modeled as two-stage, and that's not what we want.

**Comment by ekpresent** [comment]
CompressorType per https://openstudio-hpxml.readthedocs.io/en/latest/workflow_inputs.html#id362

**Comment by joseph-robertson** [comment]
@ekpresent I'm a little confused. Argument `heat_pump_cooling_compressor_type` is [already exposed](https://github.com/NREL/resstock/blob/develop/resources/hpxml-measures/BuildResidentialHPXML/measure.rb#L1239-L1242). It is optional; it is not currently called out in the lookup (and so is defaulted according to the map above), but certainly could be called out in the lookup.

Is this issue about requesting that the lookup be updated to explicitly assign values to `heat_pump_cooling_compressor_type`? Or even adding new options to the lookup for the "SEER1 16 single stage" and "SEER1 20 variable speed" scenarios you reference above?

**Comment by ekpresent** [comment]
Wait that's great. As long as we can already use that to override the default we're good to go. Didn't realize that was the case. @whiphi92
