### ISSUE TITLE
Increase HVAC sizes for existing homes?

### ISSUE THREAD

**Issue by shorowit** [NREL/resstock#1091]
Should existing homes have inflated HVAC capacities relative to ACCA calculations? This could effect, e.g., duct sizing when evaluating heat pump upgrades. 

See the discussion in the comments at the bottom of https://unmethours.com/question/91277/heat-pump-supplemental-coil-sizing-and-control-in-resstock/ (click on "see more comments").

**Comment by shorowit** [comment]
FYI @jonwinkler Something to think about for your HP sensitivities project.

**Comment by jonwinkler** [comment]
Thanks, @shorowit. We have thought about this and have a similar issue for OS-HPXML [here](https://github.com/NREL/OpenStudio-HPXML/issues/1561). Yueyue will likely start on this soon, so please let us know if you have any thoughts.

**Comment by shorowit** [comment]
Thanks! Seems like that feature will fully address this issue because it will allow every OS-HPXML user to choose the sizing factor they want to use. I'm going to close this issue then.
