### ISSUE TITLE
Water Heater Installation Location tsv

### ISSUE THREAD

**Issue by jmaguire1** [NREL/resstock#1094]
RECS2020 now has data on water heater installation location by state. Right now we use the following algorithm to default WH location:

- If in IECC Climate Zone 1-3: Install in a garage (if available), then living space.
- In all other Climate Zones: Install in basement (conditioned or unconditioned, if available), then living space.

https://github.com/NREL/resstock/blob/dae0bc189335499b766e13a46c36502f3a9d7d6a/resources/hpxml-measures/HPXMLtoOpenStudio/resources/waterheater.rb#L1408-L1420)

This will be an improvement particularly relevant for HPWHs. @lixiliu has a project that wants to explore 120 V HPWHs (which I'll be adding to OS-HPXML over the next few months), so this will be especially helpful for that project. 

Timing wise, I'll probably get started on this around end of July, this is just an early notice.

**Comment by shorowit** [comment]
@jmaguire1 I'd be interested to know if the data suggests changes to the OS-HPXML defaults for any climate zones too.

**Comment by jmaguire1** [comment]
@shorowit: Sure! This has long been something I've wanted to update but didn't realize we had data for until recently. Once I've parsed out the RECS2020 data I'll send you a note with some recommendations.
