### ISSUE TITLE
Units can have ducts in conditioned space but leakage to outside > 0

### ISSUE THREAD

**Issue by shorowit** [NREL/resstock#1095]
@lixiliu found simulations where ducts are entirely in conditioned space but have duct losses (leakage to the outside).

This is because the ResStock duct options are [defined based on leakage to outside](https://github.com/NREL/resstock/blob/48828244c3d4561b7a5c95776de3dcb30acc2337/resources/options_lookup.tsv#L1046-L1095), but the duct location is always defaulted ("auto"). When the duct location is auto, OS-HPXML will [default the ducts](https://openstudio-hpxml.readthedocs.io/en/latest/workflow_inputs.html#id603) as: `If DuctLocation not provided, defaults to the first present space type: “basement - conditioned”, “basement - unconditioned”, “crawlspace - conditioned”, “crawlspace - vented”, “crawlspace - unvented”, “attic - vented”, “attic - unvented”, “garage”, or “living space”.`

So if a dwelling unit ends up with ducts in living space or conditioned basement, it will incorrectly have some duct losses.

**My proposal**

Create a Duct Location.tsv, with dependencies on HVAC Has Ducts, Geometry Foundation Type, Geometry Attic Type, and Geometry Garage. Based on which space types are present, it would codify the OS-HPXML algorithm above. As a bonus, this will make it more explicit to a ResStock user where the ducts are located and can be used in upgrade apply logic.

Then, you could either:
1. Update Ducts.tsv to depend on Duct Location instead of HVAC Has Ducts. When Duct Location=living space or conditioned basement, always assign the "0% Leakage, Uninsulated" option. Or...
2. Zero out the duct leakage to outside inside the ResStockArguments measure when Duct Location=living space or conditioned basement. (This has the down side that the Ducts option would still show something like "20% Leakage, R-8".)

**Comment by rajeee** [comment]
Can we change the ResStockArguments "ducts_supply_leakage_to_outside_value" to "ducts_supply_leakage" instead and let OS-HPXML handle weather the leakage happens to outside or to conditioned space based on where the duct is located? It seems to me that the current leakage values in the Ducts.TSV is about the physical characteristics of the ducts and more correctly be interpreted as just a leakage and not necessarily as leakage to the outside since that depends on the placement of the duct.

**Comment by shorowit** [comment]
[This Trello card](https://trello.com/c/VmcGehGM/62-duct-leakage-total#comment-5f8de3616a50a70419a29fe5) suggests that the current leakage values are leakage to outside and the previous (pre-HPXML) were total leakage. I don't remember everything that went into that decision, whether it was for convenience of mapping to OS-HPXML or was considered a better way of describing duct leakage.

Whether the options are leakage to outside or total leakage, having a Duct Location.tsv would still have many benefits -- for example, when specifying duct sealing upgrade apply logic.

**Comment by afontani** [comment]
@shorowit : Thank you for articulating this so clearly. I like transparency. I would prefer to handle this in the characteristics. 

@rajeee : I don't think the "Duct Location.tsv" would be that difficult. Basically a bunch of 1s and 0s assigned by prune rules. Then I would suggest option 1 that Scott mentioned above. 

cc: @ekpresent , @trynthink

**Comment by ekpresent** [comment]
Are the current ducts in Ducts.tsv that have any insulation meant to represent (a) a range of physical duct characteristics for ducts that are in unconditioned space or (b) a range of portions of ducts being in unconditioned space (e.g. higher leakage values corresponding to a higher percentage of the ductwork in conditioned space)?

If (a), then we would keep the current distribution of duct leakage and insulation for ducts assigned to unconditioned space.
If (b), then we may need to do something more complicated.

**Comment by ekpresent** [comment]
@shorowit do you know the answer to my question above? Or maybe @joseph-robertson? I think our approach to fixing the issue relies on the answer to that question.

**Comment by afontani** [comment]
@ekpresent : Leakage data comes from here: https://www.pnnl.gov/main/publications/external/technical_reports/PNNL-18545.pdf. Leakage will only be applicable if the ducts are outside.

Duct insulation according to IECC 2009 (the source in Ducts.tsv) does not require insulation if the portion of the duct is completely inside the building thermal envelope.

![Image](https://github.com/NREL/resstock/assets/37630588/788f56cc-9760-4df7-8e2a-f7be5f7dc37f)

Given the data sources, the distributions should represent **Option a**.

**Comment by afontani** [comment]
Resolution during development meeting:
1. Create Duct Location.tsv following the "auto" logic
2. Fix duct leakage of ducts based on Duct Location.tsv

@lixiliu and @rajeee to coordinate the fix.
