### ISSUE TITLE
Peak reporting discrepancy

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/resstock#1096]
"qoi_report.qoi_peak_magnitude_use_kw" appears to be smaller than the max of:
* "report_simulation_output.peak_electricity_summer_total_w"
* "report_simulation_output.peak_electricity_winter_total_w"

**Comment by joseph-robertson** [comment]
I tried running datapoints 1 through 5 for the national project:

qoi_report.qoi_peak_magnitude_use_kw | report_simulation_output.peak_electricity_summer_total_w | report_simulation_output.peak_electricity_winter_total_w
-- | -- | --
5 | 4560.3 | 5002.4
11.86 | 6528.1 | 11862.3
2.62 | 2577.1 | 2620.1
2.73 | 1996.3 | 2126
6.56 | 6556.1 | 5315

Results look pretty good for datapoints 1, 2, 3, and 5.

Datapoint 4 appears to have the opposite behavior described in this issue. Winter is limited to Dec/Jan/Feb and Summer is limited to Jun/Jul/Aug, so this seems reasonable/possible to me.

@lixiliu Are you able to provide more detail here so I can reproduce the issue you are seeing?

**Comment by lixiliu** [comment]
@joseph-robertson Yes, I am seeing the discrepancy in EUSS Run Round 1 found on AWS: s3://euss/final-2018/euss_res_final_2018_550k_20220901/baseline/

Attached is a downselected version containing only building_id, total electricity, qoi_peak, and the seasonal peaks. 

I am seeing qoi_peak < seasonal peak 529469 times (out of 548916). I also noticed that the some of the seasonal peaks = 0 when total electricity is non-zero (e.g., building_id 6, 19) which makes me think that there's a bug with seasonal peaks.

[euss_amy2018_results_up00_peaks.csv](https://github.com/NREL/resstock/files/12004975/euss_amy2018_results_up00_peaks.csv)

**Comment by shorowit** [comment]
The algorithm for summer/winter peak electricity changed several months ago (see [here](https://github.com/NREL/OpenStudio-HPXML/pull/1302)). Do we know if @lixiliu's runs are using the newer algorithm? With the old algorithm, I could see how you could get this result, but not with the newer algorithm.

**Comment by shorowit** [comment]
Sorry, I wasn't very clear there. I could see how the older algorithm could give the result of "seasonal peaks = 0 when total electricity is non-zero", not how it could give the result of qoi_peak_magnitude_use_kw < max(peak_electricity_summer_total_w, peak_electricity_winter_total_w).

**Comment by joseph-robertson** [comment]
@lixiliu I can confirm that qoi vs seasonal peaks are consistent when the simulation timestep is hourly. However when the simulation timestep is subhourly (e.g., 15-minutely), I see the discrepancy similar to that reflected in your csv file posted above. Basically it comes down to [reporting peaks across hourly timesteps in QOIReport](https://github.com/NREL/resstock/blob/develop/measures/QOIReport/measure.rb#L86-L92) even if the simulation timestep is subhourly (whereas OS-HPXML reports peaks across subhourly timesteps). The following items help to illustrate what I'm talking about:
* https://github.com/NREL/resstock/issues/886
* ![image](https://github.com/NREL/resstock/assets/8516790/4ff8ac0e-921c-4ea6-88f5-1d8f1e19c60a)

**Comment by afontani** [comment]
Suggest changing name of QOI report value to something like "peak_hour..."

**Comment by shorowit** [comment]
Related: https://github.com/NREL/OpenStudio-HPXML/issues/1434
