### ISSUE TITLE
Some options in options_lookup.tsv are not in the sampling files

### ISSUE THREAD

**Issue by jmarrec** [NREL/resstock#1097]
Not sure if this is something that should be reported or not, so I'll just give one example for now (I have found more than that).

AC, SEER 14, 18, 24.5 are in the options_lookup.tsv,

https://github.com/NREL/resstock/blob/dae0bc189335499b766e13a46c36502f3a9d7d6a/resources/options_lookup.tsv#L9432-L9435

But not in the HVAC System Single Speed AC Charge (not the HVAC System Single Speed AC Airflow) TSVs:

https://github.com/NREL/resstock/blob/dae0bc189335499b766e13a46c36502f3a9d7d6a/project_national/housing_characteristics/HVAC%20System%20Single%20Speed%20AC%20Charge.tsv#L14-L17

**Comment by shorowit** [comment]
@jmarrec There's nothing inherently problematic with having options in options_lookup.tsv that are not referenced by a given project (like project_national). Also, there may be options in there that are solely used for upgrades.

**Comment by jmarrec** [comment]
I *think* I'm following why it isn't problematic. It just won't be sampled in that case I guess.

Thanks!
