### ISSUE TITLE
Other Fuel for Heating leads to no heating system?

### ISSUE THREAD

**Issue by mnblonsky** [NREL/resstock#1106]
I ran a bunch of homes in VT that have Other Fuel as the heating fuel. Other Fuel causes the Heating Efficiency to be "Other", at least most of the time. And that combo leads to "HVAC Heating Type And Fuel" to be None, see:
https://github.com/NREL/resstock/blob/30044a09fab85a00082bd5deda8c62ad969d02b6/project_national/housing_characteristics/HVAC%20Heating%20Type%20And%20Fuel.tsv#L105

That causes no heating system to get installed, which seems odd for a significant number of homes in VT. Is this a bug? Happy to share my buildstock.csv file or yaml file if that's helpful.

@lixiliu @jmaguire1

**Comment by joseph-robertson** [comment]
We actually just recently addressed this in: https://github.com/NREL/resstock/pull/947.

**Comment by rajeee** [comment]
See related issue here: https://github.com/NREL/resstock/issues/945
@mnblonsky Try with the latest version and let us know if you still have a problem.
