### ISSUE TITLE
Typo for square feet area of multi-family (33171 needs to be reduced an order of magnitude)

### ISSUE THREAD

**Issue by whiphi92** [NREL/resstock#1114]
https://github.com/NREL/resstock/blob/develop/measures/ResStockArguments/measure.rb#L401

This shows square footage for an MF housing bin of 3000-3999 to be 33171. I assume this is incorrect and a typo, but should be a quick fix.

**Comment by joseph-robertson** [comment]
Yikes!

**Comment by joseph-robertson** [comment]
Here it was: https://github.com/NREL/resstock/commit/72dd23f19ffb01b811cce8150daea3a46e85b81c.
