### ISSUE TITLE
Design temperatures being read incorrectly from newest TMY3 weather files

### ISSUE THREAD

**Issue by ekpresent** [NREL/resstock#1137]
@carlobianchi89 pushed some new TMY3 weather files recently to fix some bad sensor issues in a few specific cases. They also used 2021 ASHRAE design conditions instead of 2009, which didn't seem like it would be a problem. However, we are seeing some issues. The one we are aware of currently is that in the LA weather file, the 0.4% MCWB (2021 value: 63.5) seems to be being used as the cooling design setpoint where the 1% DB was being used before (2009 value: 82.1). Or at least that seems to be the most likely explanation so far. This is causing some pretty extreme problems with HVAC sizing. I don't know where the issue is - whether it's improperly formatted in the weather file, improperly read by OS-HPXML, or somehow a ResStock issue.

@joseph-robertson @afontani

**Comment by shorowit** [comment]
Can someone provide the before/after LA weather file?

**Comment by joseph-robertson** [comment]
I'm looking at this with @whiphi92 right now. It looks like these new TMY weather files with "2021 ASHRAE design conditions" have a new element "WSF" in their header row. Thus, offsetting by an index of 1. The OpenStudio SDK thus parses as MCWB instead of DB...

**Comment by whiphi92** [comment]
GitHub doesn't support epw files. I will send these to you on teams @shorowit

**Comment by ekpresent** [comment]
Sounds like we should just ask @carlobianchi89 to put the 2009 header on all weather files for now?

**Comment by afontani** [comment]
@carlobianchi89 and I talked and he is going to use the 2009 header to keep things consistent.

**Comment by shorowit** [comment]
> I'm looking at this with @whiphi92 right now. It looks like these new TMY weather files with "2021 ASHRAE design conditions" have a new element "WSF" in their design conditions header row. Thus, offsetting by an index of 1. The OpenStudio SDK thus parses, for example, `coolingDryBulb1` incorrectly as `coolingMeanCoincidentWetBulb1`...

The design conditions in an EPW format should reflect [this format](https://bigladdersoftware.com/epx/docs/23-1/auxiliary-programs/epw-csv-format-in-out.html#design-conditions-headerdata-csv). So it sounds like the 2021 design conditions were not properly generated.

**Comment by afontani** [comment]
This was an off-by-one error that has been fixed in the processing of the weather files.
