### ISSUE TITLE
Roof connected to living space

### ISSUE THREAD

**Issue by mnblonsky** [NREL/resstock#1152]
I have an HPXML file using ResStock 3.1 that has a hip roof connected to the living space:
```
        <Attics>
          <Attic>
            <SystemIdentifier id='Attic1'/>
            <AtticType>
              <Attic>
                <Conditioned>true</Conditioned>
              </Attic>
            </AtticType>
            <AttachedToRoof idref='Roof1'/>
            <AttachedToRoof idref='Roof2'/>
            <AttachedToRoof idref='Roof3'/>
            <AttachedToRoof idref='Roof4'/>
          </Attic>
        </Attics>
```
...
```
        <Roofs>
          <Roof>
            <SystemIdentifier id='Roof1'/>
            <InteriorAdjacentTo>living space</InteriorAdjacentTo>
```

It was made back in July using the dev branch (I think...), so it's possible that this didn't use the latest version of ResStock or that it's been fixed already. A few questions for you:
- Are hip roofs included in ResStock 3.1, or will they be included in future versions?
- Can roofs in ResStock 3.1 connect directly to the living space? It looks like this is allowed in OS-HPXML: https://openstudio-hpxml.readthedocs.io/en/latest/workflow_inputs.html#id144

Thanks!

**Comment by jmaguire1** [comment]
Taking a peek at options lookup, it seems like all attic types ("Geometry Attic Type") is all gable roofs, not hip roofs, at least in develop now? But having 4 roofs each facing a cardinal direction sure looks like a hip roof to me, so maybe at some point in the past they were an option?

Roofs CAN connect directly to the living space, that's a building with a cathedral ceiling instead of an attic.

**Comment by mnblonsky** [comment]
The building has a garage too. It looks like it may be a gable roof with a separate over the garage. In that case maybe the only issue is that the attic is included in the HPXML file, but there isn't an attic. The attic doesn't get referenced in any of the walls or roofs. Here's the HPXML file for reference.
[in.xml.txt](https://github.com/NREL/resstock/files/13127821/in.xml.txt)

**Comment by shorowit** [comment]
You can have a roof directly connected to living space for:
1. Flat roofs
2. Cathedral/vaulted ceilings (e.g., a single story home where you can see roof above you)
3. Conditioned attics (e.g., a cape cod home where there are stories with conditioned space, the top story being under the roof)

When you have a conditioned attic, there is often a collar beam and knee walls (see below) with unconditioned attic space behind them, but ResStock doesn't currently model those details.

![image](https://github.com/NREL/resstock/assets/5861765/6c1a7a64-83f8-44c5-b291-51e7c2967b28)

Many people argue a conditioned attic is not an attic at all, just another story w/ conditioned space that happens to be under the roof. I agree with them, and for similar reasons, OS-HPXML doesn't allow describing surfaces adjacent to conditioned attic, they are simply described as surfaces adjacent to living space.

**Comment by jmaguire1** [comment]
Thanks for weighing in @shorowit! Do you know if hip roofs are in ResStock by default? I don't see any options in options_lookup that say it'd be a hip roof instead of a gable roof, but looking at the .xml file there's 4 roofs and they're all between the living space and outside (ie none are garage roofs), which is making me think that this model is a gable roof. From the buildstock.csv, this home is using "Geometry Attic Type" = Finished Attic or Cathedral Ceilings, which looks like it ought to be a gable roof in the current version of develop.

I was pretty sure we always defaulted to gable roofs, but now I'm second guessing that. Here's the roofs in the hpxml file (Michael linked to it above):

```
        <Roofs>
          <Roof>
            <SystemIdentifier id='Roof1'/>
            <InteriorAdjacentTo>living space</InteriorAdjacentTo>
            <Area>1094.7</Area>
            <Orientation>west</Orientation>
            <Azimuth>270</Azimuth>
            <RoofType>asphalt or fiberglass shingles</RoofType>
            <RoofColor>medium</RoofColor>
            <SolarAbsorptance>0.85</SolarAbsorptance>
            <Emittance>0.9</Emittance>
            <InteriorFinish>
              <Type>gypsum board</Type>
              <Thickness>0.5</Thickness>
            </InteriorFinish>
            <Pitch>6.0</Pitch>
            <RadiantBarrier>false</RadiantBarrier>
            <Insulation>
              <SystemIdentifier id='Roof1Insulation'/>
              <AssemblyEffectiveRValue>29.7</AssemblyEffectiveRValue>
            </Insulation>
          </Roof>
          <Roof>
            <SystemIdentifier id='Roof2'/>
            <InteriorAdjacentTo>living space</InteriorAdjacentTo>
            <Area>1094.7</Area>
            <Orientation>east</Orientation>
            <Azimuth>90</Azimuth>
            <RoofType>asphalt or fiberglass shingles</RoofType>
            <RoofColor>medium</RoofColor>
            <SolarAbsorptance>0.85</SolarAbsorptance>
            <Emittance>0.9</Emittance>
            <InteriorFinish>
              <Type>gypsum board</Type>
              <Thickness>0.5</Thickness>
            </InteriorFinish>
            <Pitch>6.0</Pitch>
            <RadiantBarrier>false</RadiantBarrier>
            <Insulation>
              <SystemIdentifier id='Roof2Insulation'/>
              <AssemblyEffectiveRValue>29.7</AssemblyEffectiveRValue>
            </Insulation>
          </Roof>
          <Roof>
            <SystemIdentifier id='Roof3'/>
            <InteriorAdjacentTo>living space</InteriorAdjacentTo>
            <Area>235.6</Area>
            <Orientation>north</Orientation>
            <Azimuth>0</Azimuth>
            <RoofType>asphalt or fiberglass shingles</RoofType>
            <RoofColor>medium</RoofColor>
            <SolarAbsorptance>0.85</SolarAbsorptance>
            <Emittance>0.9</Emittance>
            <InteriorFinish>
              <Type>gypsum board</Type>
              <Thickness>0.5</Thickness>
            </InteriorFinish>
            <Pitch>6.0</Pitch>
            <RadiantBarrier>false</RadiantBarrier>
            <Insulation>
              <SystemIdentifier id='Roof3Insulation'/>
              <AssemblyEffectiveRValue>29.7</AssemblyEffectiveRValue>
            </Insulation>
          </Roof>
          <Roof>
            <SystemIdentifier id='Roof4'/>
            <InteriorAdjacentTo>living space</InteriorAdjacentTo>
            <Area>235.6</Area>
            <Orientation>south</Orientation>
            <Azimuth>180</Azimuth>
            <RoofType>asphalt or fiberglass shingles</RoofType>
            <RoofColor>medium</RoofColor>
            <SolarAbsorptance>0.85</SolarAbsorptance>
            <Emittance>0.9</Emittance>
            <InteriorFinish>
              <Type>gypsum board</Type>
              <Thickness>0.5</Thickness>
            </InteriorFinish>
            <Pitch>6.0</Pitch>
            <RadiantBarrier>false</RadiantBarrier>
            <Insulation>
              <SystemIdentifier id='Roof4Insulation'/>
              <AssemblyEffectiveRValue>29.7</AssemblyEffectiveRValue>
            </Insulation>
          </Roof>
        </Roofs>
```

**Comment by jmaguire1** [comment]
@mnblonsky: Did you get the answers you were looking for? If so I'll close, if not let me know and we'll get you those answers.

**Comment by mnblonsky** [comment]
Yup, I think we're all set. I think this one had a cathedral ceiling. I wasn't aware that was an option in ResStock, but it's good to know. Thanks!

**Comment by jmaguire1** [comment]
OK great! Closed
