### ISSUE TITLE
BuildStockBatch version check doesn't work

### ISSUE THREAD

**Issue by rajeee** [NREL/resstock#1155]
In my recent run attempt, I encountered this error:
`
failed with BuildStockBatch version 2023.5.0 or above is required. Found version: 2023.10.0
`
[Version checking is currently using Lexicographic comparison ](https://github.com/NREL/resstock/blob/3954b3eba9d29623e8c1672ad7b7b66cc27e8a93/resources/buildstock.rb#L558) but this doesn't work with calendar version we are using. We need to break the string by "." and compare each part separately.

**Comment by joseph-robertson** [comment]
```
irb(main):002:0> '2023.10.0' < '2023.5.0'
=> true
irb(main):003:0> Gem::Version.new('2023.10.0') < Gem::Version.new('2023.5.0')
=> false
```

We anticipated that older versions of ResStock would hit this error when trying to use BuildStockBatch v2023.10.0. I think the guidance is to either (A) update to the develop branch of ResStock, or (B) comment out the version check.

**Comment by rajeee** [comment]
Ahh, this is already fixed. Gotcha.
