### ISSUE TITLE
Data of floor area  

### ISSUE THREAD

**Issue by priyada7** [NREL/resstock#1228]
I was going through this dataset https://public.tableau.com/app/profile/nrel.buildingstock/viz/USBuildingTypologyResidential/Segments

here there is data at county level about floor area and number of buildings. May I know what’s the source of this data sets? 

Also many counties in this build stock has 3 types of air source heat pump of different seer rating. What’s the source of this data set or is it an assumption? 

I’m aware that many data sets are from RECS but if I’m not mistaken recs provide data at regional or state level right?
Thank you

**Comment by rajeee** [comment]
The sources of various characteristics used in ResStock are available here: https://github.com/NREL/resstock/blob/develop/project_national/resources/source_report.csv

**Comment by rajeee** [comment]
The python source files are currently not public.
