### ISSUE TITLE
Hot water usage seems low

### ISSUE THREAD

**Issue by jmaguire1** [NREL/resstock#1236]
We recently made a change to hot water usage multiplier to try to get a more realistic spread in hot water usage (#1210), which gives much more reasonable variability but we're realizing had an unintended effect on the mean. The original distribution was 25% of homes had multipliers of 0.5, 25% of homes had a multiplier of 2.0, and the remaining 50% had a multiplier of 1.0, which led to an overall multiplier of 1.15. With the recent change, we have an average multiplier of 0.86 (see distribution below). The combined impact of this change is our average hot water usage decreased by 1.15/0.86 = 33% In a 30k sample run I did recently, we're seeing an average hot water usage of ~35 gal/day (after filtering out vacant units). I'm digging into good data sources for what national average number we should try to target, but my first inclination is we should be pretty close to the draw volume used for medium use water heaters in the UEF test (so 55 gal/day):

![image](https://github.com/NREL/resstock/assets/8376057/f324273d-d59f-4945-9d65-1ede1a66c6bb)

Thanks to Lixi and Rajendra for helping me figure this out and trying to work out the appropriate change here.

![image](https://github.com/NREL/resstock/assets/8376057/5bc1d8e7-be48-4f9e-8302-047c292afd08)

**Comment by afontani** [comment]
The related PR for the data-driven multipliers: https://github.com/NREL/resstock/pull/1210

**Comment by shorowit** [comment]
We should coordinate/discuss this. We are looking to change the default OS-HPXML behavior for how hot water usage, as a function of number of occupants, is calculated, in which case you would ideally use multipliers with a weighted average of 1.

**Comment by jmaguire1** [comment]
So I went back to the data from the field study and shifted it so we can keep a similar spread, but have a mean be 1.0 (basically option 2 Tony described):



![Image](https://github.com/NREL/resstock/assets/8376057/bd547dec-10df-42bf-9bda-5bfeefd88694)

This is what the distribution of hot water usage multipliers would look like. Unless anyone objects to this approach, I think I'll update this in this manner. This also means that we'll be getting mean values consistent with what Scott is planning to change in terms of changing the default OS-HPXML behavior (to match this paper: https://www.fsec.ucf.edu/en/publications/pdf/fsec-pf-464-15.pdf)

**Comment by shorowit** [comment]
Related PR: https://github.com/NREL/OpenStudio-HPXML/pull/1761
