### ISSUE TITLE
Error: Element 'AssemblyEffectiveRValue': [facet 'minExclusive'] The value '0.0' must be greater than '0'.

### ISSUE THREAD

**Issue by hamzazaheers** [NREL/resstock#1237]
I am getting the following error in a bunch of my simulations. I wanted to understand what this means. Attaching the log file for details on the error. Would appreciate your 
[1.log](https://github.com/NREL/resstock/files/15179293/1.log)

**Comment by afontani** [comment]
Thank you for submitting this issue. Can you provide more information about how the log file was created? What workflow/commands you are using to create this error? 

I see that the AssemblyEffectiveRValue is 0 in this log file and the HPXML file is not created as a result. I am wondering how this model was generated.
