### ISSUE TITLE
Error: Garage is as wide as the single-family detached unit

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/resstock#1255]
Currently, it's possible in the national project to throw this error when the following combination of parameter/options is sampled:
* Geometry Building Type RECS = Single-Family Detached
* Geometry Floor Area = 0-499
* Geometry Stories = 2
* Geometry Garage = 1 Car

Garage width is 12 ft whereas the width of the building is 11.7 ft.

Possible solutions:
* reduce `geometry_garage_protrusion` to a value less than 0.75? Looks like 0.7 would work (building width becomes 12.3 ft).
* for 1 car garages, either:
  * reduce `geometry_garage_width` from 12 ft to 11 ft, or
  * reduce `geometry_garage_depth` from 24 ft to 22 ft?

**Comment by afontani** [comment]
Let's reduce the `geometry_garage_protrusion` to 0.7. I would like a 10k test to make sure we aren't hitting other errors with larger number of samples.
