### ISSUE TITLE
Unused arguments in ResStockArguments measure

### ISSUE THREAD

**Issue by shorowit** [NREL/resstock#1266]
I noticed a couple unused arguments in the ResStockArguments measure:
- `ceiling_insulation_r`
- `heat_pump_backup_use_existing_system`

Either they should be used or, if it's correct that they aren't used, they should be removed.

**Comment by joseph-robertson** [comment]
ApplyUpgrade uses them [here](https://github.com/NREL/resstock/blob/develop/measures/ApplyUpgrade/measure.rb#L367-L370) and [here](https://github.com/NREL/resstock/blob/develop/measures/ApplyUpgrade/measure.rb#L398).

**Comment by shorowit** [comment]
Thanks, I didn't consider that it might be used downstream. I'll close this then. (I guess there could be a comment next to the arguments stating they are used by ApplyUpgrade, though presumably a test would fail if someone thought they were unused and actually tried to remove them.)
