### ISSUE TITLE
How to know no of buildings used to generate the simulation in Minneapolis, MN

### ISSUE THREAD

**Issue by priyada7** [NREL/resstock#1267]
I am using https://resstock.nrel.gov/dataviewer?datasetName=vizstock_resstock_amy2018_release_2022_1_by_state_view to study the laod profiles in different state. Is there a way to know how many buildings of floor area between 2000-2500 sq ft were used to generate the load profiles?

**Comment by afontani** [comment]
@priyada7 : At the moment it might be best to use the [metatdata files](https://data.openei.org/s3_viewer?bucket=oedi-data-lake&prefix=nrel-pds-building-stock%2Fend-use-load-profiles-for-us-building-stock%2F2022%2Fresstock_amy2018_release_1.1%2Fmetadata_and_annual_results%2F) on OEDI. Here is the [file folder](https://data.openei.org/s3_viewer?bucket=oedi-data-lake&prefix=nrel-pds-building-stock%2Fend-use-load-profiles-for-us-building-stock%2F2022%2Fresstock_amy2018_release_1.1%2Fmetadata_and_annual_results%2Fby_state%2Fstate%3DMN%2Fcsv%2F) for the baseline stock and upgrade results for MN. In the "MN_baseline_metadata_and_annual_results.csv" file, check the "in.geometry_floor_area" column and filter by the 2000-24999 entry. Then count the number of lines for the number of models used. For the total number dwelling units, sum the "weight" column with the filter applied.

Results should be 1387 models and 335,836 dwelling units.
