### ISSUE TITLE
Invalid Corridor positions: ResidentialGeometryCreateMultifamily

### ISSUE THREAD

**Issue by afontani** [NREL/resstock#163]
## Invalid Corridor Positions:
In the multifamily branch and the current options_lookup.tsv, it is possible to sample the following situation for the ResidentialGeometryCreateMultifamily measure:

    num_floors: 2
    num_units: 2
    corridor_position: Double-Loaded Interior

This situation causes a runner error:

- [ResidentialGeometryCreateMultifamily/measure.rb](https://github.com/NREL/OpenStudio-BEopt/blob/58fe8c1a0f2d1be9c3fec83ae924e116cc8a1593/measures/ResidentialGeometryCreateMultifamily/measure.rb#L299 
)
## Potential Solution:

Create a new housing characteristic Corridor.  When sampled the options set the `corridor_position` argument for the ResidentialGeometryCreateMultifamily measure.
- **Dependencies:** Geometry Building Type (FPL), Geometry Stories
- **Options:** Double-Loaded Interior, Single Exterior (Front), Double Exterior, and None
- **Distributions:** Uniformally distributed to valid corridor positions or data if any is available.

**Comment by shorowit** [comment]
If it's a pain to handle on the ResStock side, a backup possibility is to modify the measure to make it a warning (instead of an error) and reset `corridor_position` to None.

**Comment by afontani** [comment]
@shorowit That is a good suggestion.  I guess it depends on how strict we want to be for other users.  Thanks.

**Comment by joseph-robertson** [comment]
I think the easiest way to handle this is just to override `Double-Loaded Interior` or `Double Exterior` with `Single Exterior (Front)` when `num_units_per_floor=1`.

**Comment by shorowit** [comment]
@joseph-robertson @afontani Is this still can issue or can it be closed?

**Comment by afontani** [comment]
@shorowit @joseph-robertson 
The Corridor.tsv seems to still have the same potential to sample a 2 floor, 2 unit double-loaded Interior corridor. However I don't remember if we updated the measure.
https://github.com/NREL/OpenStudio-BuildStock/blob/master/project_multifamily_beta/housing_characteristics/Corridor.tsv#L2

**Comment by afontani** [comment]
This no longer applies after we switched over to the single-unit workflow. PR [#439](https://github.com/NREL/resstock/pull/439)
