### ISSUE TITLE
Multifamily TSV naming conventions

### ISSUE THREAD

**Issue by mpathak24** [NREL/resstock#204]
- [x]  `geometry building type fpl` --> `geometry building type acs`
- [x]  `geometry building type` --> `geometry building type recs`
- [x]  `vintage fpl` --> `vintage bidecadal` 
- [x] Remove `Geometry Shared Walls SFA.tsv` and rename `Geometry Shared Walls MF.tsv` to `Geometry Building Shared Walls.tsv`. Add explanation to `multifamily-docs` about how derived from OSM data.
- [x] Can `geometry unit stories sf` really be 4+? Do we model that? (neither unit stories tsv are being used so remove; we'd like to just use one: `Building Floors`, but rename to `Geometry Stories.tsv` and add documentation).
- [ ] Option N/a --> None
- [x] Rename `geometry building number units hl` to `geometry_building_is_low_rise` and convert options to just low, high, none (none for all < 5)?

**Comment by shorowit** [comment]
@ejhw This can be closed?
