### ISSUE TITLE
Variability in thermostat setback times

### ISSUE THREAD

**Issue by ejhw** [NREL/resstock#214]
Don't have all samples use the same hours.

> Do we need to take a stochastic approach to generating programmable thermostat schedules for homes to capture both the potential smoothing and stacking effects? For examples, I imagine it’s more likely for an AC to cycle in the first few minutes of an hour (or maybe at the half hour) than the other times of an hour due to fact that many programmable thermostats allows scheduling to the nearest half hour. Might be particularly relevant for minute or second timescales.
> 
> I’m particularly interested in the unintended stacking as we move to more connected/programmable devices.

**Comment by shorowit** [comment]
@ejhw Has this been addressed?
[Cooling Setpoint Offset Period.tsv](https://github.com/NREL/resstock/blob/develop/project_national/housing_characteristics/Cooling%20Setpoint%20Offset%20Period.tsv)
[Heating Setpoint Offset Period.tsv](https://github.com/NREL/resstock/blob/develop/project_national/housing_characteristics/Heating%20Setpoint%20Offset%20Period.tsv)

**Comment by ejhw** [comment]
Yep, thanks!
