### ISSUE TITLE
Clarify fan schedule(s)

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/resstock#236]
The unitary system's Supply Air Fan Operating Mode Schedule Name field references a schedule that either defines Auto (zeroes) or Continuous (non-zeroes). We currently use alwaysOn and alwaysOffSchedules to achieve this, which gives the correct result but makes our measures' source code misleading. This could be improved by making our own fanAuto schedule.

Should audit the code to see if there are other similar fields.

@joseph-robertson

**Comment by shorowit** [comment]
Moved to https://github.com/NREL/OpenStudio-HPXML/issues/682
