### ISSUE TITLE
Report central system (autosized) capacities

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/resstock#250]
Right now the results csv only reports nonzero heating, cooling, and supplemental heating capacities for non-shared equipment. Shared system capacity is reported as zero because we are currently looking in the osm for non "autosized" values.

Could we get shared system capacities from the ComponentSizes table in the sql file? Should we get all system capacities from this table (instead of from the osm)?

**Comment by shorowit** [comment]
@joseph-robertson Seems like this issue no longer applies given that we are modeling individual units instead of MF buildings?

**Comment by shorowit** [comment]
In ResStock-HPXML, we report the autosized capacities for shared systems associated with the building unit.
