### ISSUE TITLE
Scaling up from "collapsed" multifamily building

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/resstock#253]
There is an issue with the scaling (SimulationOutputReport and TimeseriesCSVExport) for cases when energy consumption is fixed instead of based on floor area or number of units.

Example: a 4-unit multifamily building that is approximated using a 3-unit multifamily building (the middle unit represents 2 actual middle units). If you hardcode, e.g., `energy_use_exterior=300` for the LightingOther measure, the resulting exterior lighting energy use will be 400 instead of 300.

**Comment by shorowit** [comment]
I assume this no longer applies now that individual dwelling units are modeled?
