### ISSUE TITLE
Unrealistic multifamily building configurations

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/resstock#269]
There seems to be a recurring E+ simulation error on eagle. Attached are measures.osw and eplusout.err.

[measures.osw.txt](https://github.com/NREL/OpenStudio-BuildStock/files/3291980/measures.osw.txt)
[eplusout.err.txt](https://github.com/NREL/OpenStudio-BuildStock/files/3291981/eplusout.err.txt)

**Comment by shorowit** [comment]
Can you include an IDF?

**Comment by joseph-robertson** [comment]
[in.osm.txt](https://github.com/NREL/OpenStudio-BuildStock/files/3312074/in.osm.txt)
[in.idf.txt](https://github.com/NREL/OpenStudio-BuildStock/files/3312073/in.idf.txt)

@shorowit

**Comment by shorowit** [comment]
![image](https://user-images.githubusercontent.com/5861765/59882508-a1fee400-936f-11e9-9da0-45ac0e151a84.png)

The problem is that this unit has all adiabatic surfaces and so the heating system is sized to zero, causing an EnergyPlus error. We could prevent the EnergyPlus error, but it's not a realistic situation.

**Comment by joseph-robertson** [comment]
Talked this over with @afontani. We agree this looks weird, and should be prevented.

Our proposal for `Geometry Shared Walls SFA.tsv` and `Geometry Shared Walls MF.tsv` would be something like: have options only for `Left`, `Right`, `LeftRight`, `Back` (no double exterior), and `None`.

This would require an additional dependency on corridor type (similar to the LA project).

Generally, we feel like the testing project should be more exhaustive in terms of sampled geometry input values.

@ejhw @mpathak24

**Comment by shorowit** [comment]
@joseph-robertson This should be closed?

**Comment by shorowit** [comment]
Is this still relevant?

**Comment by joseph-robertson** [comment]
I wouldn't think so.
