### ISSUE TITLE
Data: Improve HVAC efficiency probability distributions

### ISSUE THREAD

**Issue by ejhw** [NREL/resstock#27]
"About 50% of furnace sales in 2015 met or exceeded the 92% efficiency level."
http://www.appliance-standards.org/blog/doe-takes-major-step-furnace-efficiency-standard

**Comment by afontani** [comment]
@ejhw: Was this addressed in our Age-efficiency updates after the HVAC restructure?

**Comment by ejhw** [comment]
@afontani No, but would be good to do when we update the ASHPs. 

Moved to https://github.com/NREL/resstock-estimation/issues/120
