### ISSUE TITLE
Data: Add diversity to infiltration

### ISSUE THREAD

**Issue by ejhw** [NREL/resstock#28]
Currently probability distributions for both are "single value".

**Comment by ejhw** [comment]
Splitting off setpoints issue at https://github.com/NREL/OpenStudio-BuildStock/issues/122

**Comment by ejhw** [comment]
Idea: Add tsv for WAP eligibility (y/n) that is used for infiltration and is also used when applying FPL/AMI tables in post-processing. cc @trynthink

**Comment by afontani** [comment]
Addressed here: PR [#427](https://github.com/NREL/resstock/pull/427)
