### ISSUE TITLE
Upgrade costing

### ISSUE THREAD

**Issue by shorowit** [NREL/resstock#42]
- [x] Add arguments to ApplyUpgrade measure to allow 1 or more cost values & multipliers for each option; runner.registerValue this information for upgrade options that apply.
- [x] In SimulationOutputReport reporting measure, obtain cost multiplier values (from eplusout.sql or, if needed, from the model) and combine with cost values. runner.registerValue the total upgrade cost.
- [x] For upgrade packages, only apply costs to those individual options that were applied.
- [x] Add argument for lifetime (years) to Apply Upgrade meta measure
- [x] Need a way to handle incremental costs (e.g., attic insulation going from R-20 to R-60 vs R-30 to R-60). As a workaround, one could use a package with multiple R-60 options, each of which has a different starting option apply logic and thus cost. https://github.com/NREL/resstock/pull/848

**Comment by ejhw** [comment]
I'd like to request adding a cost multiplier for `Vented attic floor area (ft^2)`.

**Comment by ejhw** [comment]
cc @trynthink

**Comment by shorowit** [comment]
I will take a stab at revamping the cost multipliers available.

**Comment by shorowit** [comment]
Attic floor area is being added in https://github.com/NREL/OpenStudio-BuildStock/pull/123.

**Comment by ejhw** [comment]
@shorowit Tracking material and labor costs separately would be beneficial for several ResStock use cases. For example, states or mfgrs may want to separate local contractor revenue (labor costs including O&P) from mfgr revenue (material costs).

1) Would it be possible to add arguments to facilitate this?
2) Can we break out this info on the Measures DB website? (alternatively we could access it from the DB directly)
