### ISSUE TITLE
EMS output variables not supported by Buildstock

### ISSUE THREAD

**Issue by mleachNREL** [NREL/resstock#423]
Custom output variables created by an EMS program cannot be written to enduse_timeseries.csv.  This requires an update to the timeseries measure:

https://github.com/NREL/OpenStudio-BuildStock/blob/master/measures/TimeseriesCSVExport/measure.rb#L100-L102

**Comment by joseph-robertson** [comment]
@mleachNREL, I think I take back what I originally told you.

As long as you have the `EnergyManagementSystem:OutputVariable` in your idf, you can request (and report in the enduse_timeseries.csv file) it by calling out its name in the `output_variables` field of the yml.

For example, if this is in your idf:
```
EnergyManagementSystem:OutputVariable,
  res gshp vert bore clg pump:Pumps:Electricity, !- Name
  unit_1_pumps_c,                         !- EMS Variable Name
  Summed,                                 !- Type of Data in Variable
  SystemTimestep,                         !- Update Frequency
  res_gshp_vert_bore_pumps_program,       !- EMS Program or Subroutine Name
  J;                                      !- Units
```
you can assign "res gshp vert bore clg pump:Pumps:Electricity" to `output_variables`, and you should see `RES GSHP VERT BORE CLG PUMP:PUMPS:ELECTRICITY (EMS) [J]` in your enduse_timeseries.csv file.

**Comment by shorowit** [comment]
I agree with @joseph-robertson. If you create the EnergyManagementSystem:OutputVariable object at the same time you create the EMS program, then you should be able to use the existing `output_variables` in the measure.
