### ISSUE TITLE
Analysis stalls out with currently queued projects

### ISSUE THREAD

**Issue by Sustainabilist** [NREL/resstock#430]
I am attempting to run an analysis, and find that it will stall out with currently queued projects. 
![image](https://user-images.githubusercontent.com/4141291/77463068-43650b80-6dc2-11ea-9b7f-45b4abb84031.png)

I have attached a picture. The queued projects never complete, and the analysis hangs permanently. I have attached the logs. 
[finalization_log.txt](https://github.com/NREL/OpenStudio-BuildStock/files/4377050/finalization_log.txt)
[rserve_log.txt](https://github.com/NREL/OpenStudio-BuildStock/files/4377051/rserve_log.txt)
[json_log.txt](https://github.com/NREL/OpenStudio-BuildStock/files/4377052/json_log.txt)

**Comment by ejhw** [comment]
If multifamily is included, it could be some fraction of large MF buildings that never complete (and never will).

**Comment by Sustainabilist** [comment]
I don't know if this helps, but his project was created from a blanked-out version of the 'singlefamily_detached' sample project. I don't think it would have multifamily included. It ran perfectly fine on 50 buildings in my test batch, and every time I changed the number of buildings after that and ran it, it stopped at some point and stalled out in this manner.

**Comment by Sustainabilist** [comment]
@ejhw - Has nobody else seen this bug? Is there some level of documentation that I need to read that I cannot find? My only thought is that because downsampling happens after selecting the buildings, non-viable buildings are being downsampled out. However, in this case, I would expect the simulation to complete but fail, instead of never running at all. 

I'd be glad to dig more if I could get a pointer on this.

**Comment by ejhw** [comment]
@Sustainabilist I'm not sure. Running on PAT/OpenStudio-Server has always had stability issues like this, and is challenging to debug. That is the main reason we're moving away from using PAT/OpenStudio-Server to buildstockbatch.

The docs for debugging PAT runs are here: https://resstock.readthedocs.io/en/v2.2.3/advanced_tutorial/debugging.html

See also: https://resstock.readthedocs.io/en/v2.2.3/aws_cluster_config.html

**Comment by shorowit** [comment]
ResStock now uses [buildstockbatch](https://github.com/NREL/buildstockbatch) instead of PAT/OpenStudio-Server, so this issue no longer applies.
