### ISSUE TITLE
Custom weather file integration and DST dates

### ISSUE THREAD

**Issue by whiphi92** [NREL/resstock#444]
When using custom weather files from historical years, the DST dates are different from what is in optionslookup.tsv. So, if I am using AMY weather files I would need to change the DST entry of the Location object for every different year. Is there a workaround for this? 

I know I have been told not to change the weather filename entry of the Location object in optionslookup.tsv so I assumed it would be the same for other entries in the Location object.

**Comment by joseph-robertson** [comment]
I think this should be a relatively easy fix/update. New to OS 3.0.0 are methods for returning daylight saving start/end dates from the epw file object. We can use these to override user-input daylight saving start/end dates for simulations that are run using AMY weather files.

**Comment by shorowit** [comment]
There has been a lot of changes related to DST since this issue was created. Does the issue still exist?

**Comment by ejhw** [comment]
Yes, still exists. This is about avoiding the need to manually change DST start/end dates for different AMY years in options_lookup.tsv.

**Comment by ejhw** [comment]
Or maybe @joseph-robertson  implemented it in #448  ?
