### ISSUE TITLE
Flexible parameter resolution for vintage, etc.

### ISSUE THREAD

**Issue by ejhw** [NREL/resstock#47]
We have a concept of hierarchical/disparate geographies (i.e., census tracts, states, regions) that can be used for defining probability distributions. Can we do something similar for non-geographic parameters? e.g., 1960s+1970s instead of separate 60s and 70s rows. This would be helpful for infiltration.
<hr>

- [ ] Add vintage bins compatible with infiltration.tsv
- [ ] Add vintage bins compatible with FPL.tsv

**Comment by shorowit** [comment]
Yes, you can certainly do this. For example, create an AggregatedVintage.tsv that depends on Vintage. All values should be 0 or 1. Then just have infiltration depend on AggregateVintages.

**Comment by shorowit** [comment]
Alternatively, you could create an AggregatedVintage.tsv that depends on Location (as the current Vintage now does) and have Vintage.tsv depend on AggregatedVintage. Then have Infiltration.tsv depend on AggregateVintages.

It's not immediately clear to me whether the two situations would produce the same results or whether one is correct and the other incorrect.

**Comment by ejhw** [comment]
This will be a higher priority because of the differing CLEAP vintage bins.
cc @trynthink

**Comment by afontani** [comment]
@ejhw: Is this still relavent?

**Comment by ejhw** [comment]
We basically accomplished this with Vintage and Vintage ACS, so no longer relevant.
