### ISSUE TITLE
Cannot find documentation for buildstock v0.18

### ISSUE THREAD

**Issue by Sashadf1** [NREL/resstock#540]
Trying to use the new ResStock v2.4.0

When clicking on the following link in the documentation under "1.3 Run the Project," http://buildstock-batch.s3-website-us..., I get the following error:

404 Not Found Code: NoSuchBucket Message: The specified bucket does not exist BucketName: buildstock-batch RequestId: 51C62ACEAD734C0A HostId: 3w7fQoXHcCgbaf/pjtfgpjY8IEsm3ozK4k7ADbhWYc/fhv1hA2TLJjJaAqxeUf9g8HPmwGcQKx4=

Please advise. I can only find the documentation for buildstockbatch 0.19, but this version is not used in conjunction with ResStock v2.4.0.

Thanks!

**Comment by joseph-robertson** [comment]
Our plan is to build buildstockbatch docs for all past versions. After that is done, I will release a ResStock v2.4.1 with an updated buildstockbatch v0.18 docs link.

**Comment by shorowit** [comment]
According to @nmerket, "the docs have been updated and there are now generated docs from several versions available at https://nrel.github.io/buildstockbatch/"
