### ISSUE TITLE
Inconsistent mini-split options

### ISSUE THREAD

**Issue by shorowit** [NREL/resstock#542]
I noticed that 2 of the 6 mini-split options in options_lookup.tsv (`master` branch) have zero supplemental heating capacity while the other 4 do (autosized).

![image](https://user-images.githubusercontent.com/5861765/106336742-cd84c880-624c-11eb-95ee-4ae32852daa1.png)

**Comment by ejhw** [comment]
Thanks for noticing this. I'd be inclined to set all to 'autosize'. Also I'd like to see these put in order of increasing efficiency.
