### ISSUE TITLE
Clothes Dryer.tsv is empty

### ISSUE THREAD

**Issue by adamsten** [NREL/resstock#552]
The Clothes Dryer.tsv is currently empty in the latest tag and in the developer branch. It used to have Fuel types with low, medium, and high usage.

Will this be returning?
Thanks!

**Comment by joseph-robertson** [comment]
@adamsten, you're talking about this file? https://github.com/NREL/resstock/blob/develop/project_national/housing_characteristics/Clothes%20Dryer.tsv

If so, it's not empty; it's huge and so github doesn't automatically render its contents.

**Comment by adamsten** [comment]
LOL. So sorry. My mistake. Thanks!
