### ISSUE TITLE
Vacancy doesn't apply to all end uses

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/resstock#562]
Currently, the following list is unaffected by vacancy:
```
# refrigerator
# extra_refrigerator
# freezer
# plug_loads_vehicle
# plug_loads_well_pump
# fuel_loads_grill
# fuel_loads_lighting
# fuel_loads_fireplace
# pool_pump
# pool_heater
# hot_tub_pump
# hot_tub_heater
```

Do we want each of these to be affected by vacancy? They are currently excluded because their corresponding schedules are not exported to `schedules.csv`.

**Comment by joseph-robertson** [comment]
We've decided to exclude the following from being affected by vacancy:
```
'refrigerator',
'extra_refrigerator',
'freezer',
'pool_pump',
'pool_heater',
'hot_tub_pump',
'hot_tub_heater'
```
Which means, we still need to have vacancy affect:
```
# plug_loads_vehicle
# plug_loads_well_pump
# fuel_loads_grill
# fuel_loads_lighting
# fuel_loads_fireplace
```

**Comment by shorowit** [comment]
Is this different than https://github.com/NREL/resstock/issues/475?

**Comment by joseph-robertson** [comment]
I believe so, yes.

**Comment by afontani** [comment]
@joseph-robertson: Isn't this just adding a "Vacancy Status" dependency to the corresponding housing characteristics?

**Comment by joseph-robertson** [comment]
I don't think so because the vacancy period in theory could be less than the whole year. Instead, I would switch these categories from using weekday/weekend/monthly schedules with `ScheduleRuleset` to using 8760 schedules with `ScheduleFile`. That way we can zero out their schedules.
