### ISSUE TITLE
Update garage and gable wall constructions for homes with CMU/brick walls

### ISSUE THREAD

**Issue by aspeake** [NREL/resstock#587]
Garage-adjacent walls and gable walls are currently modeled as wood stud walls, even if the living zone-adjacent walls are CMU or brick. We expect instances in which the following could be true:

**CMU Exterior Walls**:  CMU garage walls + wood frame gable walls
**Brick Exterior Walls**:  Brick garage walls + wood frame gable walls
**Brick Exterior Walls**:  Brick garage walls + brick gable walls

Including these scenarios would require updates to CMU walls measure and the constructions.rb file, and potentially some tsvs.

@ejhw @afontani

**Comment by shorowit** [comment]
@aspeake I see a related PR has been merged. Has this been completed?

**Comment by shorowit** [comment]
@aspeake The one right above that says "Merged". https://github.com/NREL/resstock/pull/561

**Comment by aspeake** [comment]
@shorowit no, that was related and I think uncovered this issue, but that PR did not address it.

**Comment by afontani** [comment]
@aspeake: Is this still an issue with HPXML?

**Comment by aspeake** [comment]
@afontani just ran a test with HPXML, the interzonal walls between living spaces and garages are the same as the exterior walls (CMU in my test), which is the expected/desired behavior. Gable attic walls are assumed to be wood frame, which I think is a reasonable assumption for brick and cmu walls, and may not make a huge difference in energy usage, at least for vented attics. 

The larger issue, in my opinion, was correctly considering the thermal mass in the living zone walls, which appears to be corrected.

**Comment by afontani** [comment]
@aspeake : Thanks for running some test cases. Does this mean we can close this issue?

**Comment by aspeake** [comment]
@afontani I am fine with closing it, it doesn't seem worth it to try to distribute different wall types for gable walls of brick homes.

**Comment by afontani** [comment]
@aspeake : Thanks, closing.
