### ISSUE TITLE
County -> Zipcode mapping

### ISSUE THREAD

**Issue by nmerket** [NREL/resstock#599]
For ResStock-HEScore

**Comment by afontani** [comment]
@nmerket, @aspeake: I just saw this. In resstock-estimation, we have tract-level description of housing units and their given PUMA. Given a census tract to zip-code crosswalk file, it would be pretty easy to pivot the tract table into a PUMA to zip code mapping or TSV.

**Comment by aspeake** [comment]
> 
> 
> @nmerket, @aspeake: I just saw this. In resstock-estimation, we have tract-level description of housing units and their given PUMA. Given a census tract to zip-code crosswalk file, it would be pretty easy to pivot the tract table into a PUMA to zip code mapping or TSV.

Thanks @afontani, can you point me to the tract to zip code file?

**Comment by afontani** [comment]
@aspeake: Here are the crosswalk files. Looks like they change quarterly: https://www.huduser.gov/portal/datasets/usps_crosswalk.html

**Comment by aspeake** [comment]
@afontani sorry, I mis-wrote, where is the tract to PUMA file on resstock-estimation? I just see PUMA mapped to county name in the tsvs.

**Comment by afontani** [comment]
Ah. It is created by the `sources/spatial/tsv_maker.py` or it is on s3 https://s3.console.aws.amazon.com/s3/object/resbldg-datasets?region=us-west-2&prefix=various_datasets/spatial_data/spatial_tract_lookup_table.csv

**Comment by nmerket** [comment]
This will go in hescore-hpxml as part of the resstock switch https://github.com/NREL/hescore-hpxml/issues/145

**Comment by nmerket** [comment]
@aspeake to look into getting PUMA geographic centroids and finding the closest zipcode by their centroids.

**Comment by nmerket** [comment]
Nevermind. We're gonna do a county to zipcode mapping using the file from HUD. Use the zipcode closest to the centroid of the county.

**Comment by nmerket** [comment]
@aspeake has a working implementation of this in hescore-hpxml.

**Comment by nmerket** [comment]
See https://github.com/NREL/hescore-hpxml/pull/151
