### ISSUE TITLE
Add applied option name strings to results.csv

### ISSUE THREAD

**Issue by ejhw** [NREL/resstock#637]
Currently, it is difficult to tell which options got applied under an upgrade (aka package) with multiple options in it that have different apply_logic.

We could add a column to results.csv with a concatenated list of option name strings, similar to how we sum up the costs, but would be concatenating strings instead, e.g.,
`Windows|Phius Window, Zone 1A, U-0.50, SHGC-0.25; Insulation Finished Roof|Phius Roof, Zone 1A, R-51; Insulation Wall|Phius Walls, Zone 1A, R-22; Insulation Crawlspace|Phius Fnd Walls, Zone 1A, Wall R-7, Unvented`

I think the new code would go here: https://github.com/NREL/resstock/blob/93199adafba973eae107a638ef9c1bc7c6e8d9cc/measures/SimulationOutputReport/measure.rb#L439 

This would be useful for QAQC on the several upgrade runs we have coming up in the next few weeks (Facades, ABC, Resilience).

cc @ekpresent @joseph-robertson @nmerket

**Comment by ejhw** [comment]
@joseph-robertson Actually I think we should just add a column with option name for each option. I didn't realize we were already outputting cost and lifetime for each option separately. Mock up:
![image](https://user-images.githubusercontent.com/1276021/125520331-6ad72957-7e53-477b-bcb4-7170c3c569d3.png)

**Comment by joseph-robertson** [comment]
bsb only outputs a subset of fields for `ApplyUpgrade`: https://github.com/NREL/buildstockbatch/blob/develop/buildstockbatch/postprocessing.py#L175-L183. So I will need to register option names from `SimulationOutputReport`. Spotted by @munank.
