### ISSUE TITLE
Fixed supplemental heat capacity applies to heat pump as well

### ISSUE THREAD

**Issue by zlee406** [NREL/resstock#709]
I want to autosize ASHPs for max load using a fixed capacity of supplemental heat to simulate cold climate central heat pumps without supplemental heat use. Currently, setting the `supplemental_capacity=0.0` in `options_lookup.tsv` causes the overall design heat load to be set to 0 [here](https://github.com/NREL/resstock/blob/develop/resources/measures/HPXMLtoOpenStudio/resources/hvac_sizing.rb#:~:text=if%20not%20hvac.FixedSuppHeatingCapacity.nil%3F). This means that the heat load will actually be set to the (lower) cooling capacity [here](https://github.com/NREL/resstock/blob/develop/resources/measures/HPXMLtoOpenStudio/resources/hvac_sizing.rb#:~:text=heatCap_Rated%20%3C%20unit_final.Cool_Capacity), leading to a severely undersized heat pump.

I suggest something like moving `self.process_fixed_equipment()` to after` self.process_finalize()` so that fixed sizes on supplemental heating do not affect the design loads for autosizing other equipment.

**Comment by joseph-robertson** [comment]
Closed https://github.com/NREL/resstock/pull/710.
