### ISSUE TITLE
Re-Visit Brick Wall Insulation Inputs

### ISSUE THREAD

**Issue by aspeake** [NREL/resstock#716]
Brick wall options apply insulation at the furring cavity, but the specified cavity depth is not increased to accommodate the insulation, it is instead fixed at 1 inch for all brick wall options. The cavity depth should probably align with the CMU wall options:

![image](https://user-images.githubusercontent.com/44212066/135691842-7d67a457-1753-4682-89f0-96cf6fd783d1.png)

**Comment by afontani** [comment]
@aspeake : Does this require a measure change or just options_lookup?

**Comment by aspeake** [comment]
@afontani this does not seem to be relevant with the switch to OS-HPXML, which does not break out surface layers.
