### ISSUE TITLE
Output variable naming convention

### ISSUE THREAD

**Issue by ejhw** [NREL/resstock#73]
Proposed changes to [SimulationOutputReport/measure.rb](https://github.com/NREL/OpenStudio-BuildStock/blob/master/measures/SimulationOutputReport/measure.rb). There may be some differences between Res and Com (e.g., end uses) but hope we can unite on the basics.

### Proposed changes:
1. General format & principles: `<fuel>_<end use>_<units>`. Fuel can be [electricity, natural_gas, other_fuel, source_energy, co2e]. "Site" is implied. Source and co2e are always aggregations of fuel types (calculated in post-processing). For example:
   - "electricity_total_kwh" instead of "total_site_electricity_kwh"
   - "electricity_net_kwh" instead of "net_site_electricity_kwh"
2. "lighting_interior" and "lighting_exterior" instead of "interior_lighting" and "exterior_lighting"
3. For residential, rename "water_systems" to "domestic hot water"

### Questions:
- [x] Does `OpenStudio::convert(total_val, os_units, desired_units)` interpret `MBtu` as 10e6 or 10e3.
- [ ] Is "total" the best name for whole-building consumption or is it too vague? Other options are "building", "whole_building", "facility", "meter"... OS sqlFile uses "sqlFile.electricityTotalEndUses".
- [ ] @rHorsey "total_site_energy_mbtu" or "total_site_energy_kwh"?
- [ ] @asparke2, okay to use "water_heating" instead of "water_systems"?

Eventually we'd like to split out "other fuel" into propane and fuel oil as well.

_Side note: Can we modify the code so these strings don't have to be changed in multiple places in [SimulationOutputReport/measure.rb](https://github.com/NREL/OpenStudio-BuildStock/blob/master/measures/SimulationOutputReport/measure.rb)?_

cc @joseph-robertson @shorowit @rHorsey @asparke2

**Comment by shorowit** [comment]
The answer to your first question is 10e6.

**Comment by shorowit** [comment]
water_systems is the official end use name you get from EnergyPlus.

**Comment by ejhw** [comment]
@shorowit, yes, but is that what we want to use? water_heating seems more appropriate to me (or domestic_water_heating / service_water_heating). water_systems could be interpreted as pumping, etc.

**Comment by ejhw** [comment]
@afontani I think the consensus was to not change now, but maybe revisit in July. Is that right?

**Comment by afontani** [comment]
outdated.
