### ISSUE TITLE
Power outage

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/resstock#741]
Moved from: https://trello.com/c/VhWDoKwi/54-power-outage.

Add power outage start and end dates arguments to BuildResidentialHPXML.

Checklist:
- [ ] Update more schedules than just what the schedule generator produces? (e.g., HVAC)
- [ ] Update the resilience reporting measure
- [ ] Test on buildstockbatch

**Comment by jmaguire1** [comment]
I think we'd also want to port over some capabilities I added on the resilience branch: https://github.com/NREL/resstock/tree/resilience  The two big things are changing the logic for when windows are opened such that during a summer outage the windows open when it's cooler outside than inside and adding the ability to model a "partial" outage, where users turn off non-critical loads and adjust their setpoint temperature to minimize power consumption.

**Comment by joseph-robertson** [comment]
There are basically 2 options here:

(A) Adapt the existing PowerOutage measure to be run at the end of the workflow
  - Could be easier given we have some existing code
  - More error prone, can become out of date

(B) More formally implement in the OS-HPXML workflow (e.g., add Build arguments, include more schedules, etc.)
  - We don't support detailed schedules for everything
  - Requires non smooth schedules (i.e., stochastic)

@whiphi92 @jmaguire1

**Comment by joseph-robertson** [comment]
@joseph-robertson to change the outage period convention per Scott's suggestion.
