### ISSUE TITLE
Double-check occupancy multiplier for hot water distribution

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/resstock#745]
Moved from: https://trello.com/c/XIzOhgw9/69-occupancy-driven-loads.

Drive plug loads, appliance, lighting, hot water use, etc. by # occupants vs # bedrooms?

Checklist:
- [x] Double-check occupancy multiplier for hot water distribution

**Comment by shorowit** [comment]
I took a quick look at where things stand. As far as I can tell, when there is a hot water fixtures multiplier other than 1 (indicating that there are more or fewer occupants than average according to the number of bedrooms), it appears that OS-HPXML currently:
- [Adjusts the gal/day for the fixtures' hot water](https://github.com/NREL/OpenStudio-HPXML/blob/a2aac431ef2776d1a7bfe2920dc350792f781c01/HPXMLtoOpenStudio/resources/hotwater_appliances.rb#L272)
- [Adjusts the gal/day associated with distribution](https://github.com/NREL/OpenStudio-HPXML/blob/a2aac431ef2776d1a7bfe2920dc350792f781c01/HPXMLtoOpenStudio/resources/hotwater_appliances.rb#L273)
- [Does not adjust the hot water distribution recirculation electricity use](https://github.com/NREL/OpenStudio-HPXML/blob/a2aac431ef2776d1a7bfe2920dc350792f781c01/HPXMLtoOpenStudio/resources/hotwater_appliances.rb#L290) -- probably it should make an adjustment for certain control types and not others.
- [Does not adjust the general water use internal gains](https://github.com/NREL/OpenStudio-HPXML/blob/a2aac431ef2776d1a7bfe2920dc350792f781c01/HPXMLtoOpenStudio/resources/hotwater_appliances.rb#L354) -- probably the adjustment should apply here, as it seems that most of the components (Floor mopping, shower evaporation, water films on showers, tubs & sinks surfaces, plant watering, etc.) would be sensitive to the number of occupants.

FYI @aspeake @ejhw

**Comment by shorowit** [comment]
https://github.com/NREL/OpenStudio-HPXML/pull/949

**Comment by shorowit** [comment]
I just realized there is one more component: the [EC_adj term](https://github.com/NREL/OpenStudio-HPXML/blob/d9cc8f5815582a1fec21ee279fe83fff44e0a212/HPXMLtoOpenStudio/resources/hotwater_appliances.rb#L677-L702), which applies directly to the energy consumption of the water heater. It's not obvious whether this factor needs to be separately adjusted or whether that would be double-counting the effect of occupancy given all of the adjustments we're already making. If we want to pursue this further, we have some DHW spreadsheets from Philip Fairey that might provide the necessary information to figure this out, or we might have to see if Philip can help.

**Comment by shorowit** [comment]
> I just realized there is one more component: the [EC_adj term](https://github.com/NREL/OpenStudio-HPXML/blob/d9cc8f5815582a1fec21ee279fe83fff44e0a212/HPXMLtoOpenStudio/resources/hotwater_appliances.rb#L677-L702), which applies directly to the energy consumption of the water heater. It's not obvious whether this factor needs to be separately adjusted or whether that would be double-counting the effect of occupancy given all of the adjustments we're already making. If we want to pursue this further, we have some DHW spreadsheets from Philip Fairey that might provide the necessary information to figure this out, or we might have to see if Philip can help.

@jmaguire1 Your work on https://github.com/NREL/resstock-estimation/pull/361 reminded me of this. Any thoughts?

**Comment by shorowit** [comment]
I think I've convinced myself that what we have is correct (i.e., we don't have to make an additional change to EC_adj). I ran two HPXML files (attached below) with tankless water heaters and a piping length that results in an EC_adj greater than 1. One of the HPXML files has a hot water usage multiplier of 2.0 and the other one has defaults (i.e., 1.0). The output files show that both the annual gallons of hot water doubled and the annual hot water energy use doubled. I _think_ this is the expected result.

[base-dhw-tankless-gas.xml.txt](https://github.com/NREL/resstock/files/11052879/base-dhw-tankless-gas.xml.txt)
[base-dhw-tankless-gas-2.xml.txt](https://github.com/NREL/resstock/files/11052866/base-dhw-tankless-gas-2.xml.txt)

**Comment by jmaguire1** [comment]
Sorry to be late to the party @shorowit! I've also convinced myself of the same thing: https://github.com/NREL/resstock-estimation/pull/361#issuecomment-1497986254. Basically I think since EC_adj is supposed to account for tank losses and those scale with hot water use, it seems entirely appropriate to me to keep this unmodified.
