### ISSUE TITLE
Investigate why `restructure-v3` isn't deterministic

### ISSUE THREAD

**Issue by joseph-robertson** [NREL/resstock#768]
For example, see comparisons.zip from https://github.com/NREL/resstock/actions/runs/1441711799.

**Comment by shorowit** [comment]
Also, why are there a bunch of 1s for project_testing samples in the results_characteristics.csv file in that CI run? project_national correctly shows 0s everywhere.

**Comment by shorowit** [comment]
And why does upgrades/results_outputs.csv have the following columns? (note that it goes 01 through 05, then 09, 12, 14.)

- upgrade_costs.option_01_cost_usd
- upgrade_costs.option_01_lifetime_yrs
- upgrade_costs.option_02_cost_usd
- upgrade_costs.option_02_lifetime_yrs
- upgrade_costs.option_03_cost_usd
- upgrade_costs.option_03_lifetime_yrs
- upgrade_costs.option_04_cost_usd
- upgrade_costs.option_04_lifetime_yrs
- upgrade_costs.option_05_cost_usd
- upgrade_costs.option_05_lifetime_yrs
- upgrade_costs.option_09_cost_usd
- upgrade_costs.option_09_lifetime_yrs
- upgrade_costs.option_12_cost_usd
- upgrade_costs.option_12_lifetime_yrs
- upgrade_costs.option_14_cost_usd
- upgrade_costs.option_14_lifetime_yrs

**Comment by joseph-robertson** [comment]
> Also, why are there a bunch of 1s for project_testing samples in the results_characteristics.csv file in that CI run? project_national samples correctly show 0s everywhere.

For project_testing, you'd see 1s in columns where we don't include that tsv in the project but we do for project_national.

**Comment by shorowit** [comment]
> > Also, why are there a bunch of 1s for project_testing samples in the results_characteristics.csv file in that CI run? project_national samples correctly show 0s everywhere.
> 
> For project_testing, you'd see 1s in columns where we don't include that tsv in the project but we do for project_national.

I don't follow. Wouldn't the tsv equally not apply on the master and feature branches for project_testing?

**Comment by joseph-robertson** [comment]
> > > Also, why are there a bunch of 1s for project_testing samples in the results_characteristics.csv file in that CI run? project_national samples correctly show 0s everywhere.
> > 
> > 
> > For project_testing, you'd see 1s in columns where we don't include that tsv in the project but we do for project_national.
> 
> I don't follow. Wouldn't the tsv equally not apply on the master and feature branches for project_testing?

1=NA.

**Comment by joseph-robertson** [comment]
> And why does upgrades/results_outputs.csv have the following columns? (note that it goes 01 through 05, then skips to 09, 12, 14.)
> 
> * upgrade_costs.option_01_cost_usd
> * upgrade_costs.option_01_lifetime_yrs
> * upgrade_costs.option_02_cost_usd
> * upgrade_costs.option_02_lifetime_yrs
> * upgrade_costs.option_03_cost_usd
> * upgrade_costs.option_03_lifetime_yrs
> * upgrade_costs.option_04_cost_usd
> * upgrade_costs.option_04_lifetime_yrs
> * upgrade_costs.option_05_cost_usd
> * upgrade_costs.option_05_lifetime_yrs
> * upgrade_costs.option_09_cost_usd
> * upgrade_costs.option_09_lifetime_yrs
> * upgrade_costs.option_12_cost_usd
> * upgrade_costs.option_12_lifetime_yrs
> * upgrade_costs.option_14_cost_usd
> * upgrade_costs.option_14_lifetime_yrs

Option 2 - 14 are populated due to the "package" upgrade. It skips, e.g., 6 - 8 because there is an option assigned but with no costs or lifetime values. See the [All Upgrades](https://github.com/NREL/resstock/blob/develop/project_national/national_upgrades.yml#L121-L176) upgrade for the national project. You can see that, e.g., for 100% LED lighting there are 4 options listed but only one of them has costs assigned.
