### ISSUE TITLE
ResStock-HPXML: CO2 Emissions calculations

### ISSUE THREAD

**Issue by shorowit** [NREL/resstock#790]
Leverage https://github.com/NREL/OpenStudio-HPXML/pull/937. ResStock would need to:
- [x] Add data files for the most common/recommended Cambium scenarios
- [x] Automatically apply the correct data file path(s) for any given home -- e.g., apply two scenarios (levelized LRMER and levelized SRMER data) for the RMPA region to building 1
- [x] Ensure the OS-HPXML CO2 outputs are added to the results CSV.
- [x] (Does anything special need to be done for timeseries CO2 outputs?) Need to update bsb's `residential_hpxml.py` workflow generator.
- [ ] ???

After some discussion:
- [x] Create field in yml to point to folder(s) of data files for different scenarios

**Comment by joseph-robertson** [comment]
Closed in https://github.com/NREL/resstock/pull/791.
