### ISSUE TITLE
Building stock discrepancy?

### ISSUE THREAD

**Issue by sudeepy** [NREL/resstock#811]
Hi, I'm trying to evaluate how recent resstock's building stock data is, and I came across an apparent discrepancy.

Looking at `HVAC Heating Type.tsv`, it says the data was pulled from a 2009 survey: https://github.com/NREL/resstock/blob/develop/project_national/housing_characteristics/HVAC%20Heating%20Type.tsv#:~:text=%23%20Source%3A%20Constructed%20using%20U.S.%20EIA%202009%20Residential%20Energy%20Consumption%20Survey%20(RECS)%20microdata

However, in the data, there are housing populations with vintage 2010s: https://github.com/NREL/resstock/blob/develop/project_national/housing_characteristics/HVAC%20Heating%20Type.tsv#L260-L265

How is this possible?

**Comment by sudeepy** [comment]
Bump @joseph-robertson

**Comment by JLReyna** [comment]
Building counts come from the 2017 ACS, so we have 2010s buildings in the stock. The most recent data we have for much of the equipment is the 2009 RECS survey. To bridge the gap since we don't have RECS for 2010s homes, they're modeled with the same equipment ownership as 2000s buildings.

**Comment by sudeepy** [comment]
Thanks @JLReyna!
