### ISSUE TITLE
ResStock installation instructions do not mention buildstockbatch

### ISSUE THREAD

**Issue by ejhw** [NREL/resstock#850]
Shouldn't the instructions mention that you need to download and install buildstockbatch in addition to the resstock repo?

https://resstock.readthedocs.io/en/v2.5.0/tutorial/installation.html#download-resstock

@joseph-robertson Would you be able to work on this?

**Comment by joseph-robertson** [comment]
Technically you don't _need_ to download and install buildstockbatch. You could run resstock locally using `run_analysis.rb`, as described here: https://resstock.readthedocs.io/en/latest/tutorial/run_project.html. That same page references buildstockbatch as an alternative to running locally.

**Comment by ejhw** [comment]
@joseph-robertson Thanks, I didn't realize that option had been added to the docs. Still probably good to mention installation requirements for large-scale runs on the Installation page. 

Do we have a rough threshold for what defines small scale vs large scale?

**Comment by whiphi92** [comment]
@ejhw my thought is small-scale = double digit buildings or less; large-scale = > double digit buildings. Maybe small-scale should even be smaller.

**Comment by joseph-robertson** [comment]
Just FYI. The max we run on GitHub Actions is 250, and is actually _faster_ than buildstockbatch.

I think this also depends on what your setup is: a dedicated machine would probably allow more than your personal computer. Also [note](https://github.com/NREL/resstock/blob/develop/docs/read_the_docs/source/tutorial/run_project.rst#run-using-run_analysisrb) that `run_analysis.rb` does not support `residential_quota_downselect` with `resample` right now.

**Comment by shorowit** [comment]
I have 16 cpus on my machine, I could definitely imagine running three digit (maybe even four digit) numbers of simulations.

**Comment by whiphi92** [comment]
In that case I think we should put the number at less than 1000 for small-scale, more than 1000 at large-scale. Most machines built for scientific analysis have at least 8 cpus.
