### ISSUE TITLE
Bath Fan Schedule

### ISSUE THREAD

**Issue by afontani** [NREL/resstock#858]
The bath fan schedule queried from the EULP results seems strange. The fan load shape shows the fan is on mostly at night. This is very different than the Building America Spreadsheets which seems more likely. 
<img width="1172" alt="Screen Shot 2022-03-22 at 9 28 08 AM" src="https://user-images.githubusercontent.com/37630588/159518405-1050d266-b0dc-4572-971b-384b71e22214.png">

I think the hourly load schedule should be based on the Building America Spreadsheets (probably ELCAP original data source):

hour_of_day | building_america_spreadsheets
-- | --
1 | 0.008
2 | 0.004
3 | 0.004
4 | 0.004
5 | 0.008
6 | 0.019
7 | 0.046
8 | 0.058
9 | 0.066
10 | 0.058
11 | 0.046
12 | 0.035
13 | 0.031
14 | 0.023
15 | 0.023
16 | 0.023
17 | 0.039
18 | 0.046
19 | 0.077
20 | 0.100
21 | 0.100
22 | 0.077
23 | 0.066
24 | 0.039

**Comment by joseph-robertson** [comment]
@afontani This would be an update to `Bathroom Spot Vent Hour.tsv`, right? Should this issue be transferred to resstock-estimation?

**Comment by afontani** [comment]
@joseph-robertson: Yes. That is a good point. I will transfer the issue.
