### ISSUE TITLE
FAQ omits secondary school from building type list

### ISSUE THREAD

**Issue by mcpigman** [NREL/resstock#876]
The FAQ says that there are 13 building types represented in ComStock, but the report has 14. Secondary school is the one that's missing in the FAQ.

**Comment by shorowit** [comment]
@mcpigman What FAQ are you referring to?

**Comment by mcpigman** [comment]
Perhaps I was looking at a cached version of https://comstock.nrel.gov/page/faq. It now lists 14 building types, including secondary schools. Thanks!
