### ISSUE TITLE
Fix capacity retention bandaid fix once NEEP data is standardized for HPXML

### ISSUE THREAD

**Issue by whiphi92** [NREL/resstock#880]
Reminder to fix MSHP capacity retention bandaid fix present in [this branch](https://github.com/NREL/resstock/tree/mshp-cap-retention) once NEEP ccASHP inputs have been standardized into HPXML as noted in [this](https://github.com/NREL/OpenStudio-HPXML/issues/1028) issue.

**Comment by nelsonauner** [comment]
@whiphi92  - I'm interested in working with NEEP ccASHP data in Resstock but the mentioned branch is closed. Is this issue no longer relevant? 

The most recent in-progress PR has granular details for the NEEP COP max/min/rated at various temperature points

**Comment by afontani** [comment]
Possibly available by the end of July 2023.

**Comment by joseph-robertson** [comment]
This was addressed in https://github.com/NREL/resstock/pull/1076, as a result of https://github.com/NREL/OpenStudio-HPXML/pull/1383.
