### ISSUE TITLE
Include list of included emissions scenarios

### ISSUE THREAD

**Issue by ekpresent** [NREL/resstock#881]
I've searched the resstock and openstudio-hpxml docs and I am not seeing a list of valid inputs for the emissions scenario. There is one in the example file and I can guess from there how to specify others, but it would be nice to be able to reference the list of what is included as available.

**Comment by joseph-robertson** [comment]
Are you talking about "emissions type"? If so, it can be anything: https://openstudio-hpxml.readthedocs.io/en/latest/workflow_inputs.html#id14.

There are CO2e, NOx, and SO2 defaults for natural gas, propane, and fuel oil: https://openstudio-hpxml.readthedocs.io/en/latest/workflow_inputs.html#default-values. We could document this somehow in resstock or buildstockbatch docs.

**Comment by ekpresent** [comment]
@joseph-robertson 

I just meant what the pre-computed options are called for the "scenario_name" field. I couldn't find a list when I was looking back in April. 

e.g. in the project file block here:

      - scenario_name: LRMER_MidCase_15_2025start
        type: CO2e
        elec_folder: data/cambium/LRMER_MidCase_15_2025start
        gas_value: 147.3
        propane_value: 177.8
        oil_value: 195.9
        wood_value: 200.0
