### ISSUE TITLE
Document outputs

### ISSUE THREAD

**Issue by shorowit** [NREL/resstock#882]
The documentation doesn't seem to describe what outputs are produced by ResStock. For example, it may not be immediately clear to a user that Heating does not include Heating Fans/Pumps, or that the heating/cooling loads include duct losses. Maybe it's as easy as pointing to OpenStudio-HPXML output documentation plus describing any additional ResStock-specific outputs?

**Comment by joseph-robertson** [comment]
[This](https://resstock.readthedocs.io/en/latest/tutorial/setup_analysis_project.html#build-existing-model) section of the documentation includes the following:

See the [OpenStudio-HPXML documentation](https://openstudio-hpxml.readthedocs.io/en/latest/) for information on workflow inputs and outputs.

**Comment by joseph-robertson** [comment]
@shorowit Can you describe what you are envisioning here a little more?

**Comment by shorowit** [comment]
I'm simply envisioning a top-level section after "Run the Project" called "Outputs". I would not look for information regarding outputs under "Set Up the Analysis Project", which is what you linked to above. It's fine that ResStock points to OS-HPXML for some of the outputs, but ResStock has additional output columns (like building ID, characteristics, weights, etc.).
