### ISSUE TITLE
Probably bug regarding Cambium-ResStock date alignment

### ISSUE THREAD

**Issue by ekpresent** [NREL/resstock#885]
I believe I gave @joseph-robertson bad information on Cambium.

Cambium uses 2012 weather and makes an 8760. They do this using number of hours elapsed from the beginning of the year, which preserves normal weekday/weekend patterns. This basically means that it is Dec 31 that is missing, not Feb 29.

Documentation is here: https://www.nrel.gov/docs/fy22osti/81611.pdf (Section 4.2)

I'm fairly confident that I told Joe that it was Feb 29 that was missing, and he presumably made appropriate calculations in the code based on that bad info.

**Comment by joseph-robertson** [comment]
I will include better instructions for how to obtain data: https://github.com/NREL/resstock/tree/develop/resources/data/cambium (which is probably not related to this issue).

**Comment by afontani** [comment]
What happens when we simulate a leap year and the hours are 8784 but specify 8760 emissions factors?

**Comment by shorowit** [comment]
OS-HPXML duplicates Feb 28 Cambium values for Feb 29. (Same approach that resstock-cambium used.)

**Comment by ekpresent** [comment]
I think this can probably be closed?
