### ISSUE TITLE
QOI Report peak kW conversion inconsistency?

### ISSUE THREAD

**Issue by afontani** [NREL/resstock#886]
The peak kW seem results seem to be high. The query (line 185) has `ReportingFrequency='Hourly'`, but I think it should be `ReportingFrequency='Timestep'` as the unit conversion step (line 195) includes the number of timesteps per hour. I think there might be a 4x difference in the results.

https://github.com/NREL/resstock/blob/e0050be606dbb445c39483c7a0f74fbb84280815/measures/QOIReport/measure.rb#L185-L195

**Comment by joseph-robertson** [comment]
Is the solution here to:
- (A) request only hourly Electricity:Facility timeseries and set `steps_per_hour=1`, or
- (B) request only timeseries Electricity:Facility timeseries (could be hourly or subhourly), get `steps_per_hour`, and then refactor the `timing`, `average_daily_use`, and `average_daily_timing` methods to support subhourly timeseries?

**Comment by shorowit** [comment]
Note that the OS-HPXML reporting measure produces [summer/winter peak electricity outputs](https://openstudio-hpxml.readthedocs.io/en/latest/workflow_outputs.html#peak-building-electricity).

**Comment by joseph-robertson** [comment]
@afontani Here is an implementation of (B) from above: https://github.com/NREL/resstock/pull/888.

**Comment by shorowit** [comment]
Do (A) and (B) basically give the same answer, but (B) is slower?

**Comment by joseph-robertson** [comment]
I think (A) and (B) could theoretically give different results. Consider the following example for kW during the first 2 hours.

Hourly: 0.75, 1
15-minutely: 0, 0.75, 0, 0, 0.25, 0.25, 0.25, 0.25

Hourly would assign peak at hour 2, while 15-minutely would assign peak at hour 1.

**Comment by joseph-robertson** [comment]
Leaning toward just calculating based on hourly timeseries. Which means the PR goes away, and we just need to hardcode `steps_per_hour=1`.

**Comment by joseph-robertson** [comment]
Some of the QOIReport measure outputs could probably be adopted into the OS-HPXML workflow (where we might also be able to avoid getting timeseries output).

**Comment by ejhw** [comment]
> we just need to hardcode steps_per_hour=1. 

@joseph-robertson Would this mean you can't run ResStock with a 15-min timestep?

**Comment by joseph-robertson** [comment]
Just for the reporting measure.
