### ISSUE TITLE
HVAC Heat Pump Ducted Argument Location 

### ISSUE THREAD

**Issue by whiphi92** [NREL/resstock#924]
Similar to the proposals in this comment [here](https://github.com/NREL/OpenStudio-HPXML/issues/1011#issuecomment-1102910006a), could we add  the `heat_pump_is_ducted` argument from the `HVAC Heating Type` option to the `HVAC Heating Efficiency` option so that it can be found with the other respective heat pump system arguments?

cc: @ejhw @joseph-robertson

**Comment by ejhw** [comment]
@joseph-robertson Is this line in options_lookup intentional? Shouldn't it be `None`?

Heating Fuel | None | ResStockArguments | heating_system_fuel=natural gas
-- | -- | -- | --

I'm also wondering if we should set `heating_system_fuel=electricity` in all of the electric options of `HVAC Heating Efficiency` in case that affects anything when doing upgrades?

**Comment by joseph-robertson** [comment]
@ejhw There is no acceptable "none" fuel type choice. The (arbitrary) choice of "natural gas" should be ignored for heating systems that don't consume fuel or when there is no heating system.

I think we _could_ move `heating_system_fuel=electricity` over to `HVAC Heating Efficiency`. However I think this creates an inconsistency with the other heating system fuel type options, and electric upgrades should be assuming "electricity" anyway.

**Comment by joseph-robertson** [comment]
@whiphi92 This is a little confusing to me. For example, would `HVAC Heating Efficiency=MSHP, SEER 14.5, 8.2 HSPF` get `heat_pump_is_ducted=false` or `heat_pump_is_ducted=true`? Would we need to split this MSHP option out into two, one appended with `xxx, Ducted` and the other with `xxx, Not Ducted`, or something?

**Comment by ejhw** [comment]
> @ejhw There is no acceptable "none" fuel type choice. The (arbitrary) choice of "natural gas" should be ignored for heating systems that don't consume fuel or when there is no heating system.

Got it, thanks. I don't think it is important for ResStock, but maybe we should change to `heating_system_fuel=wood` for the None option to prevent confusion or unintended downstream consequences of a hpxml file showing `heating_system_fuel=natural gas`, like knowing whether to apply a monthly customer charge for gas.
