### ISSUE TITLE
Document that heating_system_type=None is correct for heat pumps

### ISSUE THREAD

**Issue by ejhw** [NREL/resstock#932]
It is confusing that heating_system_type=None is the correct choice for heat pumps. Can we edit the description to make that clear?
https://github.com/NREL/resstock/blob/9db9b224d4d3ade8f67fc30902680a07459f03f9/resources/hpxml-measures/BuildResidentialHPXML/measure.rb#L1025-L1029

**Comment by shorowit** [comment]
It comes from having separate heat pump inputs, similar to how things are described in HPXML (`HeatingSystem`, `CoolingSystem`, or `HeatPump`). Note that it applies to `cooling_system_type` as well.

**Comment by joseph-robertson** [comment]
@ejhw You're advocating for editing descriptions of `BuildResidentialHPXML` arguments? If so, I think this issue should be moved to https://github.com/NREL/OpenStudio-HPXML/issues.

**Comment by ejhw** [comment]
Migrated to https://github.com/NREL/OpenStudio-HPXML/issues/1107
