### ISSUE TITLE
Standardize column names between run_analysis.rb and buildstockbatch

### ISSUE THREAD

**Issue by ejhw** [NREL/resstock#937]
I didn't see this outstanding need captured elsewhere. @joseph-robertson 

cc @ekpresent @afontani

**Comment by joseph-robertson** [comment]
@ejhw Was there some specific discrepancy that you were seeing?

**Comment by ejhw** [comment]
@joseph-robertson No, just remembering past comments from you and @shorowit and wanted to make sure it got captured somewhere. You may have already made them consistent a while ago.
