### ISSUE TITLE
Retain HVAC capacity for HtgSys -> HP w/ Backup HtgSys?

### ISSUE THREAD

**Issue by shorowit** [NREL/resstock#942]
Prompted by a question from @ekpresent about moving a primary heating system to backup as part of a heat pump upgrade (potentially as part of a broader package that includes envelope or other upgrades).

@shorowit:

> I suspect you're correct that if there's a HP upgrade (in which the existing heating system becomes a backup heating system) that also includes envelope improvements, both the HP and the backup system will be downsized. I'm guessing this could be addressed through an enhancement to the Apply Upgrade measure (specifically [here](https://github.com/NREL/resstock/blob/develop/measures/ApplyUpgrade/measure.rb#L346)).

@joseph-robertson:

> if you had an upgrade where you set a "new" backup system as the original primary system, then yes currently it would be autosized. i think it would be possible to update Apply Upgrade to have additional logic for checking whether the upgrade secondary system matches original primary (as well as upgrade includes setting a new primary); in this case we retain the original's size?

**Comment by ekpresent** [comment]
@whiphi92 our relevant "HP with existing heating as backup" measure is only adding a HP and not changing anything else (like appliances or facades) - can you talk through a few examples of where we're seeing different sizing? I'd think it would primarily be an issue when there were other changes packaged in.

**Comment by whiphi92** [comment]
Many of the situations getting oversized would be heating systems that are not conventional furnaces. So for example, going from a propane boiler to a MSHP with the existing propane boiler as backup. We sometimes see the existing propane boiler get sized 10-100% larger than its size in the baseline scenario.

**Comment by ekpresent** [comment]
I guess I'm confused what is changing that changes the sizing between baseline and upgrade. Is there a random element?
