### ISSUE TITLE
"Other fuel" water heaters prevent laundry energy consumption

### ISSUE THREAD

**Issue by ekpresent** [NREL/resstock#945]
Water heaters with fuels other than the big 4 (NG, electricity, propane, fuel oil) are about 0.7% of the stock according to RECS 2009. RECS 2015 and RECS 2020 combine kerosene with fuel oil and show 0.2% and 0.3% respectively using something other than NG, electricity, propane, fuel oil, or kerosene. These are low-ish numbers but not completely negligible. 

We don't model these fuels (e.g. wood, direct solar thermal, kerosene). This means that upgrading these water heaters (e.g. to HPWHs) results in apparent increased total energy consumption. That is explainable and reasonable. 

However, it looks like we also don't model these water heaters, which has downstream impacts. 

@rajeee found that every home with an "other fuel" water heater has 0 energy consumption for clothes washers and clothes dryers. When we upgrade the water heaters to HPWHs, most of the homes show typical washer and dryer energy consumption. This creates an average energy increase for clothes dryers when upgrading all water heaters to a HPWH - a result that doesn't make a lot of sense. 

@afontani found that the inputs for Water Heater Efficiency in options_lookup, when Option=Other Fuel, the arguments do not specify a water heater type (water_heater_type=none) and the setpoint is 0 degrees. He speculates there is no water flow to the washer, which means it can't run. And then I guess this means the dryer can't run either.

I assume this is not intended behavior?

**Comment by joseph-robertson** [comment]
@ejhw Do you have any insight here?

**Comment by ekpresent** [comment]
My understanding is that we are now representing in the distributions the water heaters that use "other fuel", but we don't actually model "other fuel" energy consumption. That's fine. It's out of scope. The house uses wood (or whatever), we acknowledge it uses wood, we just need to be clear that we don't model it. (It should be missing, not zero, but that's a separate issue.)

But if a house has a wood-burning water heater and a normal electric washing machine, we should be representing the washing machine's electricity consumption (for the spinning if not the heating). That's the issue I'm trying to raise.

**Comment by ekpresent** [comment]
Thoughts:
1. "there is no water heater" and "there is no water heater modeled, but there is a water heater" seem like they need to be treated differently. Once we say water heater fuel is Other and not None, we are saying there is a water heater. 

2. I honestly have no knowledge of what assumptions we should make if we model an "other fuel" water heater - that's probably a question for @jmaguire1 or @afontani ? But I am also not sure we need to model them. It's not something I've ever heard requested. I am completely fine with us not modeling onsite wood, coal, etc. as long as that is documented and as long as we are treating "downstream" things correctly. I guess the "downstream" things are internal loads and washer/dryer energy consumption. I guess it's not possible to get these approximately right without actually modeling the water heater and outputting the results?

OK, having thought all that through maybe I agree we should model them if that's the most straightforward way to get the downstream stuff approximately right.

**Comment by joseph-robertson** [comment]
@ekpresent @jmaguire1 @afontani @rajeee 
Given the direction this thread seems to take us, does #947 seem like a good approach? The summary here is that it's easiest to get downstream "laundry" modeled by enabling `Water Heater Efficiency|Other Fuel` as a "wood storage water heater" vs not modeling a water heater.
