### ISSUE TITLE
Simulations failing due to annual vs timeseries emissions mismatch.

### ISSUE THREAD

**Issue by ekpresent** [NREL/resstock#951]
@whiphi92  and I have many simulations failing with errors looking like this: 

"Timeseries outputs (21409.172) do not sum to annual output (21407.464) for Emissions: ["CO2e", "LRMER_MidCase_15"]"

They are predominantly in one upgrade, so this error may be masking some other issue. 

@rajeee said to post this as an issue.

**Comment by whiphi92** [comment]
Hey @shorowit, looks like we merged develop into run/euss on June 15th: https://github.com/NREL/resstock/commit/9e985d577116017c028fc84b2e00375c7bc80602

**Comment by ekpresent** [comment]
@rajeee asked me to zip an example building and add it - see attached.
[bldg0007061.zip](https://github.com/NREL/resstock/files/9055583/bldg0007061.zip)
